const $=s=>document.querySelector(s),L=window.PityCurve,NS='amu-web-service-lab',SLUG='pity-curve',PINGS=[];let started=false;
function metric(name){const img=new Image();PINGS.push(img);img.onload=img.onerror=()=>PINGS.splice(PINGS.indexOf(img),1);img.src=`https://api.counterapi.dev/v1/${NS}/${SLUG}-${name}/up?t=${Date.now()}`}
metric('view');try{if(!localStorage.getItem(`${SLUG}-counted`)){setTimeout(()=>{metric('visitor');localStorage.setItem(`${SLUG}-counted`,'1')},1200)}}catch(e){}
function values(){return{baseRate:Number($('#rate').value)/100,softStart:Number($('#soft').value),increase:Number($('#increase').value)/100,hardPity:Number($('#hard').value),checkpoint:Number($('#checkpoint').value)}}
function begin(){if(!started){started=true;metric('start')}}
function run(track=true){if(track)begin();const r=L.analyze(values()),maxX=Math.min(r.curve.length,Math.max(r.checkpoint,r.p99)),points=L.chartPoints(r.curve,640,220,maxX),soft=r.softStart?`<span style="left:${Math.min(100,r.softStart/maxX*100)}%">Soft ${r.softStart}</span>`:'';$('#result').innerHTML=`<div class="summary"><div class="hero-number"><small>${r.checkpoint}回までの入手率</small><strong>${L.percent(r.chanceAtCheckpoint)}</strong></div><div class="stats"><div><small>平均</small><b>${r.expected.toFixed(1)}回</b></div><div><small>50%到達</small><b>${r.median}回</b></div><div><small>90%到達</small><b>${r.p90}回</b></div><div><small>99%到達</small><b>${r.p99}回</b></div></div></div><div class="chart"><div class="chart-labels"><span>100%</span><span>50%</span><span>0%</span></div><svg viewBox="0 0 640 220" role="img" aria-label="試行回数ごとの累積入手確率"><line x1="0" y1="110" x2="640" y2="110"/><polyline points="${points}"/></svg><div class="x-axis"><span>1</span>${soft}<span>${maxX}回</span></div></div><p class="reading">同じ条件のプレイヤー100人なら、約${Math.round(r.chanceAtCheckpoint*100)}人が${r.checkpoint}回までに入手し、約${Math.round((1-r.chanceAtCheckpoint)*100)}人は未入手の見込み。</p>`;if(track)metric('complete')}
$('#calculate').addEventListener('click',run);document.querySelectorAll('input').forEach(input=>input.addEventListener('input',begin));
$('#preset').addEventListener('click',()=>{$('#rate').value='1';$('#soft').value='50';$('#increase').value='2';$('#hard').value='80';$('#checkpoint').value='60';run()});
run(false);
