const $=s=>document.querySelector(s),L=window.SaveSchemaLens,NS='amu-web-service-lab',SLUG='save-schema-lens',PINGS=[];let started=false,lastMarkdown='';
function metric(name){const img=new Image();PINGS.push(img);img.onload=img.onerror=()=>PINGS.splice(PINGS.indexOf(img),1);img.src=`https://api.counterapi.dev/v1/${NS}/${SLUG}-${name}/up?t=${Date.now()}`}
metric('view');try{if(!localStorage.getItem(`${SLUG}-counted`)){setTimeout(()=>{metric('visitor');localStorage.setItem(`${SLUG}-counted`,'1')},1200)}}catch(e){}
function begin(){if(!started&&($('#old').value.trim()||$('#next').value.trim())){started=true;metric('start')}}
$('#old').addEventListener('input',begin);$('#next').addEventListener('input',begin);
$('#sample').addEventListener('click',()=>{$('#old').value=JSON.stringify({saveVersion:1,player:{name:'Mika',level:12,coins:240},inventory:[{id:'potion',count:3}],legacyQuest:true},null,2);$('#next').value=JSON.stringify({saveVersion:'2',player:{name:'Mika',level:'12',xp:840},inventory:[{id:'potion',count:3,quality:'normal'}],settings:{volume:0.8}},null,2);begin();run()});
$('#analyze').addEventListener('click',run);
function run(){const result=L.analyze($('#old').value,$('#next').value);if(result.error){$('#result').innerHTML=`<div class="error">${result.error}</div>`;return}lastMarkdown=L.markdown(result);const items=result.changes.length?result.changes.map(c=>`<div class="change"><span class="kind ${c.severity==='high'?'high':''}">${L.label(c.kind)}</span><code>${escapeHtml(c.path)}</code><small>${c.from} → ${c.to}</small></div>`).join(''):'<div class="empty">スキーマ差分は見つからなかったよ。</div>';$('#result').innerHTML=`<div class="result-head"><div><div class="stats"><span>要対応 ${result.high}</span><span>確認 ${result.low}</span></div><h2>${result.verdict}</h2></div><span class="badge ${result.high?'danger':''}">${result.high?'MIGRATION REQUIRED':'COMPATIBLE'}</span></div><div class="changes">${items}</div>${result.high?'<div class="checklist"><h3>移行前チェック</h3><ul><li>旧データを複製して移行テスト</li><li>欠損値と型変換のフォールバックを追加</li><li>移行後データを再読込して検証</li></ul></div>':''}<button id="copy" class="ghost copy">チェックリストをコピー</button>`;$('#copy').addEventListener('click',copy);metric('complete')}
async function copy(){try{await navigator.clipboard.writeText(lastMarkdown);$('#copy').textContent='コピー済み'}catch(e){$('#copy').textContent='コピーできなかったよ'}}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
