(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.DeadlineBuffer=api})(typeof self!=='undefined'?self:this,function(){
  const DAY=86400000;
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  function normalizeTask(task,index){let low=Math.max(0,Number(task.low)||0),likely=Math.max(0,Number(task.likely)||0),high=Math.max(0,Number(task.high)||0);const sorted=[low,likely,high].sort((a,b)=>a-b);return{name:String(task.name||`工程 ${index+1}`).trim()||`工程 ${index+1}`,low:sorted[0],likely:sorted[1],high:sorted[2]}}
  function triangular(u,a,m,b){if(b<=a)return a;const f=(m-a)/(b-a);return u<f?a+Math.sqrt(u*(b-a)*(m-a)):b-Math.sqrt((1-u)*(b-a)*(b-m))}
  function rng(seed){let x=seed>>>0;return()=>{x=(x*1664525+1013904223)>>>0;return x/4294967296}}
  function percentile(values,p){if(!values.length)return 0;const a=[...values].sort((x,y)=>x-y),i=(a.length-1)*clamp(p,0,1),lo=Math.floor(i),hi=Math.ceil(i);return a[lo]+(a[hi]-a[lo])*(i-lo)}
  function addWorkDays(start,days){const d=new Date(`${start}T12:00:00Z`);if(Number.isNaN(d.getTime()))return null;let whole=Math.floor(Math.max(0,days)),fraction=Math.max(0,days)-whole;while(whole>0){d.setUTCDate(d.getUTCDate()+1);const w=d.getUTCDay();if(w!==0&&w!==6)whole--}if(fraction>0){d.setTime(d.getTime()+fraction*DAY);while(d.getUTCDay()===0||d.getUTCDay()===6)d.setUTCDate(d.getUTCDate()+1)}return d}
  function workDaysBetween(start,end){let a=new Date(`${start}T12:00:00Z`),b=new Date(`${end}T12:00:00Z`);if(Number.isNaN(a)||Number.isNaN(b)||b<a)return 0;let n=0;while(a<b){a.setUTCDate(a.getUTCDate()+1);if(a.getUTCDay()!==0&&a.getUTCDay()!==6)n++}return n}
  const iso=d=>d?d.toISOString().slice(0,10):'—';
  function analyze(rawTasks,weeklyHours,start,target,runs=5000,seed=260807){const tasks=rawTasks.map(normalizeTask).filter(t=>t.high>0),capacity=Math.max(.5,Number(weeklyHours)||0)/5,random=rng(seed),hours=[];for(let i=0;i<runs;i++)hours.push(tasks.reduce((sum,t)=>sum+triangular(random(),t.low,t.likely,t.high),0));const workDays=hours.map(h=>h/capacity),p50=percentile(workDays,.5),p80=percentile(workDays,.8),p90=percentile(workDays,.9),available=target?workDaysBetween(start,target):null,chance=available===null?null:Math.round(workDays.filter(d=>d<=available).length/workDays.length*100),likelyHours=tasks.reduce((s,t)=>s+t.likely,0);return{tasks,capacity,likelyHours,p50,p80,p90,p50Date:iso(addWorkDays(start,p50)),p80Date:iso(addWorkDays(start,p80)),p90Date:iso(addWorkDays(start,p90)),available,chance,runs}}
  function report(result,start,target){return['# Deadline Buffer','',`開始日: ${start}`,`目標納期: ${target||'未指定'}`,`週の制作時間: ${(result.capacity*5).toFixed(1)}h`,`工程数: ${result.tasks.length}`,'',`P50: ${result.p50Date}（${result.p50.toFixed(1)}稼働日）`,`P80: ${result.p80Date}（${result.p80.toFixed(1)}稼働日）`,`P90: ${result.p90Date}（${result.p90.toFixed(1)}稼働日）`,target?`目標納期内の完了確率: ${result.chance}%`:'','',...result.tasks.map(t=>`- ${t.name}: ${t.low}h / ${t.likely}h / ${t.high}h`),'','※ 独立した三角分布による概算。割り込み、並行作業、休日、工程間の相関は含みません。'].filter(Boolean).join('\n')}
  return{clamp,normalizeTask,triangular,percentile,addWorkDays,workDaysBetween,analyze,report};
});
