(function(root){
'use strict';
const round=(n,d=2)=>Number(n.toFixed(d));
function positive(value,label){const n=Number(value);if(!Number.isFinite(n)||n<=0)throw new Error(`${label}は0より大きい数値にしてね`);return n}
function parseDevices(text){const rows=String(text||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map((line,index)=>{const p=line.split(/[,\t]/).map(x=>x.trim());if(p.length<3)throw new Error(`端末 ${index+1} は 名前,幅,高さ で入力してね`);return{name:p[0]||`端末${index+1}`,width:positive(p[1],`端末 ${index+1} の幅`),height:positive(p[2],`端末 ${index+1} の高さ`)}});if(!rows.length)throw new Error('端末を1件以上入力してね');if(rows.length>12)throw new Error('端末は12件までだよ');return rows}
function scaleFor(screenW,screenH,refW,refH,match){const widthScale=screenW/refW,heightScale=screenH/refH;return 2**((1-match)*Math.log2(widthScale)+match*Math.log2(heightScale))}
function analyze(settings,devices){const refW=positive(settings.refW,'基準幅'),refH=positive(settings.refH,'基準高さ'),elementW=positive(settings.elementW,'UI幅'),elementH=positive(settings.elementH,'UI高さ'),minimumPx=positive(settings.minimumPx,'最小辺しきい値'),match=Number(settings.match);if(!Number.isFinite(match)||match<0||match>1)throw new Error('Matchは0〜1にしてね');const rows=devices.map(device=>{const scale=scaleFor(device.width,device.height,refW,refH,match),canvasW=device.width/scale,canvasH=device.height/scale,renderedW=elementW*scale,renderedH=elementH*scale,shortSide=Math.min(renderedW,renderedH);return{...device,scale:round(scale,4),widthScale:round(device.width/refW,4),heightScale:round(device.height/refH,4),canvasW:round(canvasW,1),canvasH:round(canvasH,1),renderedW:round(renderedW,1),renderedH:round(renderedH,1),shortSide:round(shortSide,1),status:shortSide<minimumPx?'small':'ok'}});const smallest=rows.reduce((a,b)=>a.shortSide<=b.shortSide?a:b),spread=Math.max(...rows.map(x=>x.shortSide))/Math.min(...rows.map(x=>x.shortSide));return{settings:{refW,refH,match,elementW,elementH,minimumPx},summary:{devices:rows.length,smallCount:rows.filter(x=>x.status==='small').length,smallestDevice:smallest.name,smallestPx:smallest.shortSide,sizeSpread:round(spread,2),verdict:rows.some(x=>x.status==='small')?'しきい値未満あり':'全端末で基準内'},rows}}
function exportData(result){return{tool:'Canvas Scale Deck',version:1,createdAt:new Date().toISOString(),method:'Unity Canvas Scaler / Scale With Screen Size の対数補間式を再現。物理サイズやOS倍率は含まない。',...result}}
root.CanvasScaleDeck={parseDevices,scaleFor,analyze,exportData};
})(typeof window!=='undefined'?window:globalThis);
