(function(root){'use strict';
const clean=v=>String(v||'').trim();
const rows=text=>clean(text).split(/\r?\n/).map(x=>x.trim()).filter(Boolean);
const tags=v=>[...new Set(clean(v).split(/[,、]/).map(x=>x.trim().toLowerCase()).filter(Boolean))];
function parseChanges(text){return rows(text).map((line,i)=>{const p=line.split('|').map(clean);const risk=Math.max(1,Math.min(5,Number(p[1])||3));return{name:p[0]||`変更${i+1}`,risk,tags:tags(p[2]),check:p[3]||`${p[0]||`変更${i+1}`}の主要動作を確認`}})}
function parseTargets(text){return rows(text).map((line,i)=>{const p=line.split('|').map(clean);const importance=Math.max(1,Math.min(3,Number(p[1])||2));return{name:p[0]||`環境${i+1}`,importance,tags:tags(p[2])}})}
function intersect(a,b){return a.filter(x=>b.includes(x))}
function build(input){const name=clean(input.name)||'次回リリース',budget=Math.max(15,Math.min(1440,Number(input.budget)||90)),changes=parseChanges(input.changes),targets=parseTargets(input.targets);if(!changes.length)throw new Error('変更領域を1件以上入力してね');if(!targets.length)throw new Error('対象環境を1件以上入力してね');if(changes.length>30||targets.length>20)throw new Error('変更30件、環境20件までだよ');
 const cases=[];targets.forEach(t=>cases.push({kind:'smoke',change:'全体',target:t.name,score:30+t.importance*5,minutes:6,reason:'起動・主要導線・終了の最低確認',check:'起動、主要画面遷移、保存または終了まで確認'}));
 changes.forEach(c=>targets.forEach(t=>{const shared=intersect(c.tags,t.tags);const score=c.risk*10+t.importance*4+shared.length*7;const minutes=c.risk>=5?14:c.risk>=4?11:8;cases.push({kind:'regression',change:c.name,target:t.name,score,minutes,reason:shared.length?`関連タグ: ${shared.join(', ')}`:`リスク${c.risk} × 重要度${t.importance}`,check:c.check})}));
 cases.sort((a,b)=>b.score-a.score||a.minutes-b.minutes||a.target.localeCompare(b.target,'ja'));let used=0;cases.forEach(x=>x.selected=false);const choose=x=>{if(!x.selected&&used+x.minutes<=budget){x.selected=true;used+=x.minutes;return true}return false};
 // まず各環境の最低動作、次に各変更の最重要な組み合わせを1件ずつ確保し、残り時間を総合スコア順で埋める。
 targets.forEach(t=>choose(cases.find(x=>x.kind==='smoke'&&x.target===t.name)));changes.slice().sort((a,b)=>b.risk-a.risk).forEach(c=>choose(cases.find(x=>x.kind==='regression'&&x.change===c.name)));cases.forEach(choose);if(!cases.some(x=>x.selected)&&cases.length){cases[0].selected=true;used=cases[0].minutes}
 const selected=cases.filter(x=>x.selected).sort((a,b)=>(a.kind==='smoke'?-1:1)-(b.kind==='smoke'?-1:1)||b.score-a.score),deferred=cases.filter(x=>!x.selected),coveredChanges=new Set(selected.filter(x=>x.kind==='regression').map(x=>x.change)),coveredTargets=new Set(selected.map(x=>x.target));return{name,budget,used,changes,targets,cases,selected,deferred,coverage:{changes:coveredChanges.size,totalChanges:changes.length,targets:coveredTargets.size,totalTargets:targets.length},warning:coveredChanges.size<changes.length?'予算内で未確認の変更領域がある':'変更領域をすべて1回以上確認できる'}}
function markdown(r){const list=r.selected.map((x,i)=>`${i+1}. [ ] **${x.change} / ${x.target}**（${x.minutes}分）\n   - ${x.check}\n   - 優先理由: ${x.reason}`).join('\n');const later=r.deferred.slice(0,12).map(x=>`- ${x.change} / ${x.target}（${x.minutes}分）`).join('\n')||'- なし';return `# ${r.name} リリースゲート\n\n- テスト予算: ${r.budget}分\n- 採用: ${r.selected.length}件 / ${r.used}分\n- 変更カバー: ${r.coverage.changes}/${r.coverage.totalChanges}\n- 環境カバー: ${r.coverage.targets}/${r.coverage.totalTargets}\n- 判定: ${r.warning}\n\n## 今回実行する確認\n${list}\n\n## 予算外\n${later}\n`}
function exportData(r){return{tool:'Release Gate Deck',version:1,createdAt:new Date().toISOString(),...r}}
root.ReleaseGateDeck={parseChanges,parseTargets,build,markdown,exportData};})(typeof window!=='undefined'?window:globalThis);
