(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.LayerSieve=api})(typeof self!=='undefined'?self:this,function(){
  const ROLES=['actor','world','projectile','trigger','sensor','ui','other'];
  function parse(text){const layers=[],errors=[],seen=new Set();String(text||'').split(/\r?\n/).forEach((line,i)=>{const raw=line.trim();if(!raw||raw.startsWith('#'))return;const [nameRaw,roleRaw='other']=raw.split(',').map(x=>x.trim()),name=nameRaw.slice(0,40),role=roleRaw.toLowerCase();if(!name||seen.has(name.toLowerCase())||!ROLES.includes(role)||layers.length>=20){errors.push({line:i+1,text:raw});return}seen.add(name.toLowerCase());layers.push({name,role,index:layers.length})});return{layers,errors}}
  const key=(a,b)=>[a,b].sort((x,y)=>x-y).join(':');
  function normalizePairs(pairs,count){const set=new Set();(pairs||[]).forEach(p=>{const a=Number(p[0]),b=Number(p[1]);if(Number.isInteger(a)&&Number.isInteger(b)&&a>=0&&b>=0&&a<count&&b<count&&a!==b)set.add(key(a,b))});return set}
  function audit(layers,pairs){const enabled=normalizePairs(pairs,layers.length),issues=[],degrees=layers.map(()=>0);enabled.forEach(k=>{const [a,b]=k.split(':').map(Number);degrees[a]++;degrees[b]++});layers.forEach((l,i)=>{if(l.role!=='ui'&&degrees[i]===0)issues.push({level:'error',layer:l.name,message:'どのレイヤーとも衝突しない'});if(l.role==='ui'&&degrees[i]>0)issues.push({level:'warn',layer:l.name,message:'UIレイヤーに物理衝突が設定されている'});if(layers.length>3&&degrees[i]>=Math.ceil((layers.length-1)*.8))issues.push({level:'warn',layer:l.name,message:`全体の${Math.round(degrees[i]/(layers.length-1)*100)}%と衝突する高密度設定`})});
    layers.forEach((l,i)=>{const targets=layers.map((x,j)=>({x,j})).filter(({j})=>enabled.has(key(i,j)));if(l.role==='actor'&&!targets.some(t=>t.x.role==='world'))issues.push({level:'error',layer:l.name,message:'actorにworldとの衝突がない'});if(l.role==='projectile'&&!targets.some(t=>['actor','world'].includes(t.x.role)))issues.push({level:'error',layer:l.name,message:'projectileにactor/worldとの衝突がない'});if(['trigger','sensor'].includes(l.role)&&!targets.some(t=>t.x.role==='actor'))issues.push({level:'warn',layer:l.name,message:`${l.role}にactorとの接触がない`})});
    const possible=layers.length*(layers.length-1)/2;return{issues,degrees,enabled:[...enabled],enabledCount:enabled.size,possible,density:possible?enabled.size/possible:0,errors:issues.filter(x=>x.level==='error').length,warnings:issues.filter(x=>x.level==='warn').length}}
  function unityScript(layers,pairs){const enabled=normalizePairs(pairs,layers.length),lines=['// Layer Sieve: disabled collision pairs','void ApplyCollisionMatrix()','{'];for(let a=0;a<layers.length;a++)for(let b=a+1;b<layers.length;b++)if(!enabled.has(key(a,b)))lines.push(`    Physics.IgnoreLayerCollision(LayerMask.NameToLayer("${layers[a].name.replaceAll('"','\\"')}"), LayerMask.NameToLayer("${layers[b].name.replaceAll('"','\\"')}"), true);`);lines.push('}');return lines.join('\n')}
  function report(layers,pairs){const result=audit(layers,pairs);return{generated_at:new Date().toISOString(),layers:layers.map(({name,role})=>({name,role})),enabled_pairs:result.enabled.map(k=>{const[a,b]=k.split(':').map(Number);return[layers[a].name,layers[b].name]}),summary:{enabled:result.enabledCount,possible:result.possible,density:result.density,errors:result.errors,warnings:result.warnings},issues:result.issues}}
  return{ROLES,parse,key,normalizePairs,audit,unityScript,report};
});
