(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ClearRateLens=api})(typeof self!=='undefined'?self:this,function(){
  function clamp(value,min,max){return Math.max(min,Math.min(max,value))}
  function wilson(successes,trials,z=1.96){if(!trials)return{low:0,high:1,center:0,margin:1};const p=successes/trials,z2=z*z,den=1+z2/trials,center=(p+z2/(2*trials))/den,margin=z*Math.sqrt((p*(1-p)+z2/(4*trials))/trials)/den;return{low:clamp(center-margin,0,1),high:clamp(center+margin,0,1),center,margin}}
  function parseCSV(text){const lines=String(text||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!lines.length)return[];const start=/attempt|試行/i.test(lines[0])?1:0;return lines.slice(start).map((line,index)=>{const parts=line.split(/[,\t]/).map(x=>x.trim());return{name:parts[0]||`Stage ${index+1}`,attempts:Number(parts[1]),clears:Number(parts[2]),target:Number(parts[3])}})}
  function analyze(rows){return(rows||[]).map((raw,index)=>{const name=String(raw.name||`Stage ${index+1}`).trim(),attempts=Math.max(0,Math.floor(Number(raw.attempts)||0)),clears=clamp(Math.floor(Number(raw.clears)||0),0,attempts),target=clamp((Number(raw.target)||0)/100,0,1),rate=attempts?clears/attempts:0,ci=wilson(clears,attempts);let signal='insufficient',label='データ不足';if(attempts>0){if(ci.high<target){signal='hard';label='目標より難しい'}else if(ci.low>target){signal='easy';label='目標より易しい'}else{signal='uncertain';label='目標範囲と重なる'}}const desiredMargin=.1,needed=Math.ceil(1.96*1.96*.25/(desiredMargin*desiredMargin)),more=Math.max(0,needed-attempts);return{name,attempts,clears,target,rate,ci,signal,label,delta:rate-target,more}})}
  function summary(results){const valid=results.filter(x=>x.attempts>0);return{stages:results.length,attempts:valid.reduce((s,x)=>s+x.attempts,0),hard:valid.filter(x=>x.signal==='hard').length,easy:valid.filter(x=>x.signal==='easy').length,uncertain:valid.filter(x=>x.signal==='uncertain').length,insufficient:results.filter(x=>x.signal==='insufficient').length}}
  function exportData(results){return{generated_at:new Date().toISOString(),method:'Wilson score interval, 95%',note:'区間が目標を完全に下回る場合は難しい、上回る場合は易しい。重なる場合は追加観測を優先。',summary:summary(results),stages:results.map(x=>({name:x.name,attempts:x.attempts,clears:x.clears,target_percent:+(x.target*100).toFixed(1),observed_percent:+(x.rate*100).toFixed(1),ci95_percent:[+(x.ci.low*100).toFixed(1),+(x.ci.high*100).toFixed(1)],signal:x.signal,additional_attempts_for_10pp_margin:x.more}))}}
  return{wilson,parseCSV,analyze,summary,exportData};
});
