const $=s=>document.querySelector(s),G=window.ContactSheetStudio,SLUG='contact-sheet-studio',NS='amu-web-service-lab',PINGS=[];let items=[],result=null,started=false,completed=false;
function metric(name){const image=new Image;PINGS.push(image);image.onload=image.onerror=()=>PINGS.splice(PINGS.indexOf(image),1);image.src=`https://api.counterapi.dev/v1/${NS}/${SLUG}-${name}/up?t=${Date.now()}`}
metric('view');try{if(!localStorage.getItem(`${SLUG}-counted`))setTimeout(()=>{metric('visitor');localStorage.setItem(`${SLUG}-counted`,'1')},1200)}catch(e){}
function loadImage(src,name){return new Promise((resolve,reject)=>{const img=new Image;img.onload=()=>resolve({name,img,width:img.naturalWidth,height:img.naturalHeight,sourceWidth:img.naturalWidth,sourceHeight:img.naturalHeight,src});img.onerror=()=>reject(new Error(`${name} を読み込めませんでした`));img.src=src})}
async function addFiles(files){$('#error').textContent='';const valid=[...files].filter(f=>f.type.startsWith('image/'));if(!valid.length){$('#error').textContent='画像ファイルを選んでください';return}try{const loaded=await Promise.all(valid.map(async f=>{const url=URL.createObjectURL(f);try{return await loadImage(url,f.name)}catch(e){URL.revokeObjectURL(url);throw e}}));items.push(...loaded);renderQueue()}catch(e){$('#error').textContent=e.message}}
function renderQueue(){const q=$('#queue');q.innerHTML='';items.forEach(item=>{const row=document.createElement('div');row.className='item';const im=document.createElement('img');im.src=item.src;const name=document.createElement('span');name.textContent=`${item.name}　${item.width}×${item.height}`;row.append(im,name);q.append(row)});if(!items.length)q.innerHTML='<p>画像はまだないよ。</p>';$('#summary').textContent=items.length?`${items.length}枚を準備中`:'画像を追加してね'}
function makeSample(name,w,h,colors,mark){const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><defs><linearGradient id="g" x2="1" y2="1"><stop stop-color="${colors[0]}"/><stop offset="1" stop-color="${colors[1]}"/></linearGradient></defs><rect width="100%" height="100%" rx="30" fill="url(#g)"/><circle cx="${w*.68}" cy="${h*.36}" r="${Math.min(w,h)*.2}" fill="#fff" opacity=".16"/><path d="M${w*.12} ${h*.72} Q${w*.38} ${h*.22} ${w*.58} ${h*.72}T${w*.9} ${h*.64}" fill="none" stroke="#fff" stroke-width="${Math.max(6,w/55)}" opacity=".82"/><text x="${w*.08}" y="${h*.18}" fill="#fff" font-family="sans-serif" font-size="${Math.max(22,w/14)}" font-weight="700">${mark}</text></svg>`;return loadImage(URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'})),name)}
async function sample(){try{items=await Promise.all([makeSample('forest-wide.png',800,450,['#14532d','#22c55e'],'A / WIDE'),makeSample('sky-portrait.png',450,700,['#1e3a8a','#38bdf8'],'B / TALL'),makeSample('sunset-square.png',560,560,['#7c2d12','#fb7185'],'C / SQUARE')]);renderQueue();build(true)}catch(e){$('#error').textContent=e.message}}
function build(track=true){try{if(track&&!started){metric('start');started=true}result=G.layout(items,{columns:$('#columns').value,cellWidth:$('#cellWidth').value,cellHeight:$('#cellHeight').value,labels:$('#labels').checked,gap:20,padding:28});const c=$('#canvas'),ctx=c.getContext('2d');c.width=result.width;c.height=result.height;ctx.fillStyle=$('#background').value;ctx.fillRect(0,0,c.width,c.height);result.cells.forEach(cell=>{ctx.drawImage(cell.img,cell.x,cell.y,cell.width,cell.height);if(result.labelHeight){ctx.fillStyle='#edf4ff';ctx.font='600 17px system-ui,sans-serif';const max=result.cellWidth-8;let label=cell.name;while(label.length>5&&ctx.measureText(label).width>max)label=label.slice(0,-2);if(label!==cell.name)label+='…';ctx.fillText(label,cell.labelX,cell.labelY)}});$('#summary').textContent=`${items.length}枚 / ${result.columns}列 × ${result.rows}行`;$('#size').textContent=`${result.width} × ${result.height}px`;$('#download').disabled=$('#manifest').disabled=false;$('#error').textContent='';if(track&&!completed){metric('complete');completed=true}}catch(e){$('#error').textContent=e.message}}
function saveBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('#files').onchange=e=>addFiles(e.target.files);$('#sample').onclick=sample;$('#build').onclick=()=>build(true);$('#download').onclick=()=>$('#canvas').toBlob(blob=>blob&&saveBlob(blob,'contact-sheet.png'),'image/png');$('#manifest').onclick=()=>result&&saveBlob(new Blob([JSON.stringify(G.manifest(result),null,2)],{type:'application/json'}),'contact-sheet-layout.json');
const drop=$('#drop');['dragenter','dragover'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.add('over')}));['dragleave','drop'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.remove('over')}));drop.addEventListener('drop',e=>addFiles(e.dataTransfer.files));
