const $=s=>document.querySelector(s),L=window.ChannelPacker,SLUG='channel-packer',NS='amu-web-service-lab',PINGS=[],NAMES=['r','g','b','a'],LABELS={r:'R / Metallic',g:'G / Occlusion',b:'B / Mask',a:'A / Smoothness'};let sources={},result=null,started=false,completed=false;
function metric(n){const im=new Image;PINGS.push(im);im.onload=im.onerror=()=>PINGS.splice(PINGS.indexOf(im),1);im.src=`https://api.counterapi.dev/v1/${NS}/${SLUG}-${n}/up?t=${Date.now()}`}
metric('view');try{if(!localStorage.getItem(`${SLUG}-counted`))setTimeout(()=>{metric('visitor');localStorage.setItem(`${SLUG}-counted`,'1')},1200)}catch(e){}
function build(){const root=$('#channels');root.innerHTML=NAMES.map(n=>`<article class="channel ${n}"><h3><span>${LABELS[n]}</span><small id="dim-${n}">sample</small></h3><label class="file"><input id="file-${n}" type="file" accept="image/png,image/webp,image/jpeg"><strong id="name-${n}">画像を選択</strong></label><div class="options"><label>読取<select id="mode-${n}"><option value="luma">輝度</option><option value="red">Red</option><option value="green">Green</option><option value="blue">Blue</option><option value="alpha">Alpha</option></select></label><label>未使用時の値<input id="fallback-${n}" type="number" min="0" max="255" value="${n==='a'?255:0}"></label></div><label class="check"><input id="enabled-${n}" type="checkbox" checked> この入力を使う</label><label class="check"><input id="invert-${n}" type="checkbox"> 白黒を反転</label></article>`).join('');NAMES.forEach(n=>{$(`#file-${n}`).onchange=e=>load(n,e.target.files[0])})}
function restore(){sources=L.sample(256);NAMES.forEach(n=>{$(`#name-${n}`).textContent=sources[n].label+' sample';$(`#dim-${n}`).textContent='256×256';$(`#enabled-${n}`).checked=true;$(`#invert-${n}`).checked=false;$(`#mode-${n}`).value='luma'});$('#width').value=$('#height').value=256;pack(false)}
function load(name,file){if(!file)return;const im=new Image,url=URL.createObjectURL(file);im.onload=()=>{const c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(im,0,0);sources[name]={data:g.getImageData(0,0,c.width,c.height).data,width:c.width,height:c.height,label:file.name};$(`#name-${name}`).textContent=file.name;$(`#dim-${name}`).textContent=`${c.width}×${c.height}`;$('#width').value=c.width;$('#height').value=c.height;URL.revokeObjectURL(url)};im.onerror=()=>{$('#error').textContent='画像を読み込めなかった';URL.revokeObjectURL(url)};im.src=url}
function settings(){return Object.fromEntries(NAMES.map(n=>[n,{enabled:$(`#enabled-${n}`).checked,mode:$(`#mode-${n}`).value,invert:$(`#invert-${n}`).checked,fallback:Math.max(0,Math.min(255,Number($(`#fallback-${n}`).value)||0)),label:sources[n]?.label||'constant'}]))}
function draw(data,w,h){const c=$('#output');c.width=w;c.height=h;c.getContext('2d').putImageData(new ImageData(data,w,h),0,0)}
function pack(track=true){try{const w=Number($('#width').value),h=Number($('#height').value);if(!started&&track){metric('start');started=true}const config=settings();result={data:L.pack(sources,w,h,config),width:w,height:h,settings:config};draw(result.data,w,h);const st=L.stats(result.data);$('#stats').innerHTML=NAMES.map(n=>`<article><small>${n.toUpperCase()} range</small><b>${st[n].min}–${st[n].max}</b><span>平均 ${st[n].mean}</span></article>`).join('');$('#summary').textContent='RGBAを合成したよ';$('#dimensions').textContent=`${w}×${h}`;$('#png').disabled=$('#json').disabled=false;$('#error').textContent='';$('#status').textContent='入力は外部送信せず、端末内で合成したよ。';if(track&&!completed){metric('complete');completed=true}}catch(e){$('#error').textContent=e.message}}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800)}
function savePng(){if(!result)return;const c=document.createElement('canvas');c.width=result.width;c.height=result.height;c.getContext('2d').putImageData(new ImageData(result.data,result.width,result.height),0,0);c.toBlob(b=>download(b,'packed-rgba.png'),'image/png');$('#status').textContent='RGBA PNGを保存したよ。'}
function saveJson(){if(!result)return;const report=L.report(result.data,result.width,result.height,result.settings);download(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}),'packed-rgba-settings.json');$('#status').textContent='割当設定と出力統計をJSONに保存したよ。'}
build();$('#sample').onclick=restore;$('#pack').onclick=()=>pack(true);$('#png').onclick=savePng;$('#json').onclick=saveJson;restore();
