(function(root){'use strict';
const rad=Math.PI/180,deg=180/Math.PI,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function shortestDelta(from,to){let d=(Number(to)-Number(from))%360;if(d>180)d-=360;if(d<=-180)d+=360;return d}
function unwrap(values){if(!values.length)return[];const out=[Number(values[0])];for(let i=1;i<values.length;i++)out.push(out[i-1]+shortestDelta(values[i-1],values[i]));return out}
function quaternion(yaw,pitch,roll){const x=pitch*rad/2,y=yaw*rad/2,z=roll*rad/2,cx=Math.cos(x),sx=Math.sin(x),cy=Math.cos(y),sy=Math.sin(y),cz=Math.cos(z),sz=Math.sin(z);return{x:sx*cy*cz+cx*sy*sz,y:cx*sy*cz-sx*cy*sz,z:cx*cy*sz+sx*sy*cz,w:cx*cy*cz-sx*sy*sz}}
function angleBetween(a,b){const dot=Math.abs(a.x*b.x+a.y*b.y+a.z*b.z+a.w*b.w);return 2*Math.acos(clamp(dot,-1,1))*deg}
function parse(text){const lines=String(text||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const rows=[];for(let i=0;i<lines.length;i++){const p=lines[i].split(/[\t,;]/).map(x=>x.trim());if(i===0&&!Number.isFinite(Number(p[0])))continue;if(p.length<4)throw new Error(`${i+1}行目は time, yaw, pitch, roll の4列にしてね`);const nums=p.slice(0,4).map(Number);if(!nums.every(Number.isFinite))throw new Error(`${i+1}行目に数値でない値があるよ`);rows.push({time:nums[0],yaw:nums[1],pitch:nums[2],roll:nums[3]})}if(rows.length<3)throw new Error('ヘッダーを除いて3行以上の回転サンプルが必要だよ');for(let i=1;i<rows.length;i++)if(rows[i].time<=rows[i-1].time)throw new Error('timeは昇順かつ重複なしにしてね');return rows}
function analyze(text,options={}){const rows=parse(text),speedLimit=Number(options.speedLimit??540),accelLimit=Number(options.accelLimit??4000);if(!(speedLimit>0)||!(accelLimit>0))throw new Error('速度・加速度の上限は0より大きくしてね');const yaw=unwrap(rows.map(r=>r.yaw)),pitch=unwrap(rows.map(r=>r.pitch)),roll=unwrap(rows.map(r=>r.roll));const segments=[];let previousSpeed=null;for(let i=1;i<rows.length;i++){const a=rows[i-1],b=rows[i],dt=b.time-a.time,rawJump=Math.max(Math.abs(b.yaw-a.yaw),Math.abs(b.pitch-a.pitch),Math.abs(b.roll-a.roll)),axisDelta={yaw:yaw[i]-yaw[i-1],pitch:pitch[i]-pitch[i-1],roll:roll[i]-roll[i-1]},angle=angleBetween(quaternion(a.yaw,a.pitch,a.roll),quaternion(b.yaw,b.pitch,b.roll)),speed=angle/dt,accel=previousSpeed===null?0:Math.abs(speed-previousSpeed)/dt,wrapArtifact=rawJump>180&&angle<90;const flags=[];if(wrapArtifact)flags.push('Euler折返し');if(speed>speedLimit)flags.push('角速度超過');if(previousSpeed!==null&&accel>accelLimit)flags.push('角加速度超過');segments.push({from:i-1,to:i,time:a.time,dt,rawJump,axisDelta,angle,speed,accel,wrapArtifact,flags});previousSpeed=speed}const flagged=segments.filter(s=>s.flags.length),wraps=segments.filter(s=>s.wrapArtifact),peakSpeed=Math.max(...segments.map(s=>s.speed)),peakAccel=Math.max(...segments.map(s=>s.accel)),duration=rows.at(-1).time-rows[0].time,verdict=!flagged.length?'連続性は良好':wraps.length===flagged.length?'Euler表記の折返しのみ':'実回転のスパイク候補あり';const corrected=rows.map((r,i)=>({time:r.time,yaw:yaw[i],pitch:pitch[i],roll:roll[i]}));const actions=[];if(wraps.length)actions.push(`${wraps.length}区間は±180°境界の見かけ上のジャンプ。補正CSVかQuaternion補間を使う`);if(segments.some(s=>s.speed>speedLimit))actions.push(`角速度 ${peakSpeed.toFixed(1)}°/s が上限 ${speedLimit}°/s を超える区間をカーブ編集で確認する`);if(segments.some(s=>s.accel>accelLimit))actions.push(`角加速度 ${peakAccel.toFixed(0)}°/s² の急変があるため、隣接キーの接線か補間方式を確認する`);if(!actions.length)actions.push('設定した速度・加速度上限内。実機では補間方式とフレーム間隔も確認する');return{rows,corrected,segments,flagged,wraps,peakSpeed,peakAccel,duration,speedLimit,accelLimit,verdict,actions}}
function correctedCsv(result){return'time,yaw_unwrapped,pitch_unwrapped,roll_unwrapped\n'+result.corrected.map(r=>[r.time,...['yaw','pitch','roll'].map(k=>Number(r[k].toFixed(4)))].join(',')).join('\n')+'\n'}
root.RotationWrapGuard={shortestDelta,unwrap,quaternion,angleBetween,parse,analyze,correctedCsv};})(typeof window!=='undefined'?window:globalThis);
