(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.LODDistanceLens=api})(typeof self!=='undefined'?self:this,function(){
  const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
  function parseLevels(text){return String(text||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map((line,index)=>{const p=line.split(/[,\t]/).map(x=>x.trim());return{name:p[0]||`LOD${index}`,triangles:Math.max(0,Math.floor(Number(p[1])||0)),threshold:clamp((Number(p[2])||0)/100,0,1)}}).filter(x=>x.triangles>0&&x.threshold>0)}
  function parseBands(text){return String(text||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(line=>{const p=line.split(/[,\t]/).map(Number);return{distance:Math.max(.01,p[0]||0),count:Math.max(0,Math.floor(p[1]||0))}}).filter(x=>x.count>0)}
  function relativeHeight(objectHeight,distance,fov){const radians=clamp(Number(fov)||60,1,179)*Math.PI/180;return clamp((Math.max(0,Number(objectHeight)||0)/(2*Math.max(.01,distance)*Math.tan(radians/2))),0,1)}
  function transitionDistance(objectHeight,fov,threshold){const radians=clamp(Number(fov)||60,1,179)*Math.PI/180;return Math.max(0,Number(objectHeight)||0)/(2*Math.max(.0001,threshold)*Math.tan(radians/2))}
  function audit(levels){const issues=[];if(!levels.length)issues.push('有効なLODがない');for(let i=1;i<levels.length;i++){if(levels[i].threshold>=levels[i-1].threshold)issues.push(`${levels[i].name}: 画面比率は前段より小さくする`);if(levels[i].triangles>=levels[i-1].triangles)issues.push(`${levels[i].name}: 三角形数が前段以上`)}return issues}
  function analyze(config){const height=Math.max(.01,Number(config.objectHeight)||1),fov=clamp(Number(config.fov)||60,1,179),levels=(config.levels||[]).slice(),bands=config.bands||[],issues=audit(levels);const transitions=levels.map(x=>({...x,distance:transitionDistance(height,fov,x.threshold)}));const rows=bands.map(b=>{const screen=relativeHeight(height,b.distance,fov),index=levels.findIndex(x=>screen>=x.threshold),level=index>=0?levels[index]:null,triangles=level?level.triangles*b.count:0;return{...b,screen,index,name:level?level.name:'Culled',triangles}});const instances=rows.reduce((s,x)=>s+x.count,0),baseline=instances*(levels[0]?.triangles||0),projected=rows.reduce((s,x)=>s+x.triangles,0),saved=baseline-projected;return{height,fov,levels,transitions,rows,issues,instances,baseline,projected,saved,savedRate:baseline?saved/baseline:0}}
  function exportData(result){return{generated_at:new Date().toISOString(),model:'Perspective vertical screen-height approximation',assumptions:['Object height uses world-space bounds','Distances are camera-to-object center approximations','Occlusion, batching, shadows and GPU vertex cost are not included'],object_height:result.height,vertical_fov:result.fov,summary:{instances:result.instances,baseline_triangles:result.baseline,projected_triangles:result.projected,reduction_percent:+(result.savedRate*100).toFixed(1)},lods:result.transitions.map(x=>({name:x.name,triangles:x.triangles,screen_relative_height_percent:+(x.threshold*100).toFixed(2),approx_transition_distance:+x.distance.toFixed(2)})),distance_bands:result.rows.map(x=>({distance:x.distance,count:x.count,screen_height_percent:+(x.screen*100).toFixed(2),selected:x.name,triangles:x.triangles})),issues:result.issues}}
  return{parseLevels,parseBands,relativeHeight,transitionDistance,audit,analyze,exportData};
});
