(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.BlendSpaceCompass=api})(typeof self!=='undefined'?self:this,function(){
  const clean=v=>String(v??'').trim(),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  function parseRows(text){const lines=clean(text).split(/\r?\n/).map(clean).filter(Boolean);if(!lines.length)throw new Error('モーションを1行以上入力してね');return lines.map((line,index)=>{const cells=line.split(',').map(clean);if(cells.length!==3)throw new Error(`${index+1}行目: Motion,X,Y の3列が必要`);const [name,xRaw,yRaw]=cells,x=Number(xRaw),y=Number(yRaw);if(!name)throw new Error(`${index+1}行目: Motion名は必須`);if(!Number.isFinite(x)||!Number.isFinite(y)||Math.abs(x)>1000||Math.abs(y)>1000)throw new Error(`${index+1}行目: XとYは-1000〜1000の数値にしてね`);return{name,x,y,line:index+1}})}
  const angleOf=p=>(Math.atan2(p.y,p.x)*180/Math.PI+360)%360;
  const angleDiff=(a,b)=>Math.abs(((a-b+540)%360)-180);
  function analyze(rows,settings={}){const centerRadius=Number(settings.centerRadius??0.08),oppositeTolerance=Number(settings.oppositeTolerance??20);if(!Number.isFinite(centerRadius)||centerRadius<0||centerRadius>10)throw new Error('中心半径は0〜10にしてね');if(!Number.isFinite(oppositeTolerance)||oppositeTolerance<1||oppositeTolerance>90)throw new Error('対向許容角は1〜90度にしてね');const seen=new Map,duplicates=[];for(const row of rows){const key=`${row.x}\u0000${row.y}`;if(seen.has(key))duplicates.push({first:seen.get(key),second:row.name,x:row.x,y:row.y});else seen.set(key,row.name)}const samples=rows.map(p=>({...p,radius:Math.hypot(p.x,p.y),angle:angleOf(p)})),center=samples.filter(p=>p.radius<=centerRadius),directional=samples.filter(p=>p.radius>centerRadius).sort((a,b)=>a.angle-b.angle);let largestGap=360,gapStart=null,gapEnd=null;if(directional.length>=2){largestGap=-1;for(let i=0;i<directional.length;i++){const a=directional[i].angle,b=i===directional.length-1?directional[0].angle+360:directional[i+1].angle,gap=b-a;if(gap>largestGap){largestGap=gap;gapStart=a;gapEnd=b%360}}}else if(directional.length===1){gapStart=directional[0].angle;gapEnd=directional[0].angle;}
    const detailed=directional.map(p=>{const target=(p.angle+180)%360,nearest=directional.filter(q=>q!==p).reduce((best,q)=>Math.min(best,angleDiff(q.angle,target)),180);return{...p,oppositeError:nearest,hasOpposite:nearest<=oppositeTolerance}});const oppositeRate=detailed.length?detailed.filter(p=>p.hasOpposite).length/detailed.length*100:0,sectors=Array.from({length:8},(_,i)=>({label:['右','右上','上','左上','左','左下','下','右下'][i],count:0}));for(const p of directional)sectors[Math.round(p.angle/45)%8].count++;const missingSectors=sectors.filter(x=>!x.count).map(x=>x.label),radii=directional.map(x=>x.radius),meanRadius=radii.length?radii.reduce((a,b)=>a+b,0)/radii.length:0,variance=radii.length?radii.reduce((s,x)=>s+(x-meanRadius)**2,0)/radii.length:0,radiusCV=meanRadius?Math.sqrt(variance)/meanRadius*100:0;const warnings=[];if(!center.length)warnings.push('中心付近のIdleサンプルがない');if(center.length>1)warnings.push('中心付近に複数サンプルが重なっている');if(duplicates.length)warnings.push(`同一座標が${duplicates.length}組ある`);if(largestGap>90)warnings.push(`方向の最大空白が${largestGap.toFixed(1)}°ある`);if(oppositeRate<75)warnings.push('対向モーションが不足している');if(radiusCV>25)warnings.push('外周サンプルの強度差が大きい');const score=clamp(Math.round(100-(center.length?0:15)-duplicates.length*10-Math.max(0,largestGap-45)*.35-(100-oppositeRate)*.25-Math.max(0,radiusCV-15)*.4),0,100);return{settings:{centerRadius,oppositeTolerance},summary:{sampleCount:samples.length,centerCount:center.length,directionalCount:directional.length,largestGap,oppositeRate,radiusCV,score},gap:{start:gapStart,end:gapEnd,size:largestGap},samples,center,directional:detailed,sectors,missingSectors,duplicates,warnings,status:warnings.length?'review':'balanced'}}
  function exportData(result){return{generated_at:new Date().toISOString(),model:'2D blend-space directional coverage audit',assumptions:['X and Y are normalized or comparable blend parameters','Samples inside centerRadius are treated as center/idle','Angular coverage does not simulate Unity blend weights or animation quality'],settings:result.settings,summary:result.summary,gap:result.gap,sectors:result.sectors,duplicates:result.duplicates,warnings:result.warnings,samples:result.samples.map(({line,...x})=>x)}}
  return{parseRows,analyze,exportData,angleDiff};
});
