const $=s=>document.querySelector(s),L=window.SfxSeedLab,NS='amu-web-service-lab',SLUG='sfx-seed-lab',PINGS=[];let current='coin',started=false,completed=false,serial=101,audio;
function metric(name){const img=new Image();PINGS.push(img);img.onload=img.onerror=()=>PINGS.splice(PINGS.indexOf(img),1);img.src=`https://api.counterapi.dev/v1/${NS}/${SLUG}-${name}/up?t=${Date.now()}`}
metric('view');try{if(!localStorage.getItem(`${SLUG}-counted`)){setTimeout(()=>{metric('visitor');localStorage.setItem(`${SLUG}-counted`,'1')},1200)}}catch(e){}
function begin(){if(!started){started=true;metric('start')}}function finish(){if(!completed){completed=true;metric('complete')}}
function values(){return L.normalize({startHz:$('#startHz').value,endHz:$('#endHz').value,duration:$('#duration').value,noise:$('#noise').value,wave:$('#wave').value,seed:serial})}
function setValues(p){const n=L.normalize(p);for(const k of ['startHz','endHz','duration','noise'])$('#'+k).value=n[k];$('#wave').value=n.wave;serial=n.seed;render()}
function draw(data){const c=$('#scope'),ctx=c.getContext('2d'),d=devicePixelRatio||1,r=c.getBoundingClientRect(),w=Math.max(300,r.width),h=w*280/760;if(c.width!==Math.round(w*d)){c.width=Math.round(w*d);c.height=Math.round(h*d)}ctx.setTransform(c.width/760,0,0,c.height/280,0,0);ctx.clearRect(0,0,760,280);ctx.fillStyle='#07131a';ctx.fillRect(0,0,760,280);ctx.strokeStyle='#ffffff0c';ctx.lineWidth=1;for(let x=0;x<=760;x+=38){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,280);ctx.stroke()}for(let y=0;y<=280;y+=35){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(760,y);ctx.stroke()}ctx.strokeStyle='#6fffd2';ctx.shadowColor='#6fffd2';ctx.shadowBlur=10;ctx.lineWidth=2;ctx.beginPath();for(let x=0;x<760;x++){const i=Math.min(data.length-1,Math.floor(x/759*data.length)),y=140-data[i]*112;x?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke();ctx.shadowBlur=0}
function render(){const p=values(),data=L.synth(p);$('#startHzOut').value=p.startHz+' Hz';$('#endHzOut').value=p.endHz+' Hz';$('#durationOut').value=p.duration+' ms';$('#noiseOut').value=p.noise+'%';$('#durationLabel').textContent=p.duration+' ms';$('#presetName').textContent=current.toUpperCase();$('#recipe').textContent=L.recipe(p);draw(data)}
async function play(){begin();const p=values(),data=L.synth(p);audio=audio||new (window.AudioContext||window.webkitAudioContext)();await audio.resume();const b=audio.createBuffer(1,data.length,L.RATE);b.copyToChannel(data,0);const source=audio.createBufferSource(),gain=audio.createGain();source.buffer=b;gain.gain.value=.55;source.connect(gain).connect(audio.destination);source.start();$('#status').textContent='生成音を再生したよ。';draw(data)}
function choose(name){current=name;document.querySelectorAll('[data-preset]').forEach(b=>b.classList.toggle('active',b.dataset.preset===name));setValues(L.PRESETS[name])}
document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{begin();choose(b.dataset.preset)}));for(const id of ['startHz','endHz','duration','noise','wave'])$('#'+id).addEventListener('input',()=>{begin();current='custom';document.querySelectorAll('[data-preset]').forEach(b=>b.classList.remove('active'));render()});$('#play').addEventListener('click',play);$('#scope').addEventListener('pointerdown',play);$('#randomize').addEventListener('click',()=>{begin();serial=(serial+7919)%2147483646;current='variant';document.querySelectorAll('[data-preset]').forEach(b=>b.classList.remove('active'));setValues(L.mutate(values(),serial));$('#status').textContent='少し違う候補を作ったよ。'});$('#download').addEventListener('click',()=>{begin();const blob=new Blob([L.wavBytes(L.synth(values()))],{type:'audio/wav'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`sfx-${current}-${Date.now()}.wav`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);finish();$('#status').textContent='WAVを保存したよ。'});choose('coin');
