const $=s=>document.querySelector(s),L=window.CooldownWeave,SLUG='cooldown-weave',NS='amu-web-service-lab',PINGS=[];let started=false,completed=false;
function metric(name){const img=new Image();PINGS.push(img);img.onload=img.onerror=()=>PINGS.splice(PINGS.indexOf(img),1);img.src=`https://api.counterapi.dev/v1/${NS}/${SLUG}-${name}/up?t=${Date.now()}`}
metric('view');try{if(!localStorage.getItem(`${SLUG}-counted`)){setTimeout(()=>{metric('visitor');localStorage.setItem(`${SLUG}-counted`,'1')},1200)}}catch(e){}
function begin(){if(!started){started=true;metric('start')}}function finish(){if(!completed){completed=true;metric('complete')}}
const model={horizon:30,abilities:[{name:'Guard',cooldown:8,duration:3,offset:0},{name:'Dash',cooldown:6,duration:1.5,offset:3},{name:'Barrier',cooldown:14,duration:4,offset:6}]};
function controls(){const root=$('#abilityControls');root.innerHTML='';model.abilities.forEach((a,i)=>{const el=document.createElement('section');el.className='ability';el.innerHTML=`<div class="ability-title"><i class="dot" style="background:${L.COLORS[i]}"></i>${a.name}</div><div class="triple"><label>再使用<input type="number" min="1" max="60" step="0.5" value="${a.cooldown}" data-i="${i}" data-k="cooldown"></label><label>効果時間<input type="number" min="0.1" max="30" step="0.5" value="${a.duration}" data-i="${i}" data-k="duration"></label><label>初回<input type="number" min="0" max="60" step="0.5" value="${a.offset}" data-i="${i}" data-k="offset"></label></div>`;root.append(el)});root.querySelectorAll('input').forEach(input=>input.addEventListener('input',()=>{begin();model.abilities[+input.dataset.i][input.dataset.k]=input.value;render()}))}
function track(name,intervals,color,cover=false){const row=document.createElement('div');row.className='track'+(cover?' cover':'');row.innerHTML=`<span class="track-name">${name}</span><div class="rail"></div>`;const rail=row.lastElementChild;intervals.forEach(x=>{const b=document.createElement('i');b.className='block';b.style.left=x.start/model.horizon*100+'%';b.style.width=(x.end-x.start)/model.horizon*100+'%';b.style.background=color;rail.append(b)});return row}
function render(){model.horizon=+$('#horizon').value;const a=L.analyze(model);$('#horizonOut').value=a.horizon+'秒';$('#axisMid').textContent=a.horizon/2+'s';$('#axisEnd').textContent=a.horizon+'s';$('#coverage').textContent=a.coverage+'%';$('#gap').textContent=a.longestGap+'秒';$('#uses').textContent=a.uses;const t=$('#timeline');t.innerHTML='';a.tracks.forEach(x=>t.append(track(x.name,x.intervals,x.color)));const merged=L.mergeIntervals(a.tracks.flatMap(x=>x.intervals),a.horizon);t.append(track('全体カバー',merged,'#e9e8df',true));const v=$('#verdict');v.className='verdict '+a.status;v.textContent=a.status==='strong'?`カバー率${a.coverage}%。空白は最大${a.longestGap}秒で、ローテーションは連続性が高い。`:a.status==='mixed'?`カバー率${a.coverage}%。最大${a.longestGap}秒の空白を、初回発動か再使用時間で調整できる。`:`カバー率${a.coverage}%。最大${a.longestGap}秒の空白があり、効果切れを意図した設計か確認が必要。`}
$('#horizon').addEventListener('input',()=>{begin();render()});$('#copy').addEventListener('click',()=>{begin();const text=L.exportText(model);$('#jsonOutput').textContent=text;$('#jsonOutput').hidden=false;const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();const copied=document.execCommand('copy');area.remove();$('#copyStatus').textContent=copied?'設計JSONを表示し、コピーしたよ。':'設計JSONを表示したよ。';finish()});controls();render();
