(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.CooldownWeave=api})(this,function(){
  const COLORS=['#ffcf4a','#68e0c3','#a998ff','#ff7895'];
  function clamp(value,min,max){const n=Number(value);return Math.min(max,Math.max(min,Number.isFinite(n)?n:min))}
  function round(value,digits=1){const p=10**digits;return Math.round((Number(value)+Number.EPSILON)*p)/p}
  function normalize(input={}){const horizon=round(clamp(input.horizon,10,120));const source=Array.isArray(input.abilities)?input.abilities:[];const abilities=source.slice(0,4).map((a,i)=>({name:String(a.name||`Action ${i+1}`).slice(0,24),cooldown:round(clamp(a.cooldown,1,60)),duration:round(clamp(a.duration,.1,30)),offset:round(clamp(a.offset,0,60)),color:COLORS[i]}));return{horizon,abilities}}
  function intervalsFor(a,horizon){const rows=[];for(let start=a.offset;start<horizon;start+=a.cooldown)rows.push({start:round(start),end:round(Math.min(horizon,start+a.duration)),name:a.name,color:a.color});return rows}
  function mergeIntervals(intervals,horizon){const sorted=intervals.map(x=>({start:x.start,end:x.end})).sort((a,b)=>a.start-b.start||a.end-b.end),merged=[];for(const row of sorted){if(row.end<=0||row.start>=horizon)continue;if(!merged.length||row.start>merged[merged.length-1].end)merged.push({...row});else merged[merged.length-1].end=Math.max(merged[merged.length-1].end,row.end)}return merged}
  function analyze(input={}){const n=normalize(input),tracks=n.abilities.map(a=>({...a,intervals:intervalsFor(a,n.horizon)})),all=tracks.flatMap(t=>t.intervals),merged=mergeIntervals(all,n.horizon);let covered=merged.reduce((s,x)=>s+x.end-x.start,0),gaps=[],cursor=0;for(const x of merged){if(x.start>cursor)gaps.push({start:round(cursor),end:round(x.start),length:round(x.start-cursor)});cursor=Math.max(cursor,x.end)}if(cursor<n.horizon)gaps.push({start:round(cursor),end:n.horizon,length:round(n.horizon-cursor)});covered=round(covered);const coverage=round(covered/n.horizon*100);return{...n,tracks,covered,coverage,longestGap:gaps.length?Math.max(...gaps.map(g=>g.length)):0,gaps,uses:all.length,status:coverage>=90?'strong':coverage>=65?'mixed':'weak'}}
  function exportData(input={}){const a=analyze(input);return{horizonSeconds:a.horizon,coveragePercent:a.coverage,longestGapSeconds:a.longestGap,gaps:a.gaps,abilities:a.abilities.map(({color,...x})=>x),note:'Each action is assumed to trigger automatically at offset + n × cooldown.'}}
  function exportText(input){return JSON.stringify(exportData(input),null,2)}
  return{COLORS,clamp,round,normalize,intervalsFor,mergeIntervals,analyze,exportData,exportText};
});
