const assert=require('assert'),L=require('./logic');
assert.strictEqual(L.clamp('9',1,5),5);
assert.deepStrictEqual(L.normalize({horizon:3,abilities:[{name:'Guard',cooldown:0,duration:50,offset:-2}]}),{horizon:10,abilities:[{name:'Guard',cooldown:1,duration:30,offset:0,color:'#ffcf4a'}]});
let rows=L.intervalsFor({name:'A',cooldown:5,duration:2,offset:1,color:'x'},12);
assert.deepStrictEqual(rows.map(x=>[x.start,x.end]),[[1,3],[6,8],[11,12]]);
assert.deepStrictEqual(L.mergeIntervals([{start:0,end:3},{start:2,end:5},{start:8,end:9}],10),[{start:0,end:5},{start:8,end:9}]);
let a=L.analyze({horizon:20,abilities:[{name:'A',cooldown:10,duration:5,offset:0},{name:'B',cooldown:10,duration:5,offset:5}]});
assert.strictEqual(a.coverage,100);
assert.strictEqual(a.longestGap,0);
assert.strictEqual(a.uses,4);
assert.strictEqual(a.status,'strong');
a=L.analyze({horizon:20,abilities:[{name:'A',cooldown:10,duration:2,offset:0}]});
assert.strictEqual(a.coverage,20);
assert.strictEqual(a.longestGap,8);
assert.deepStrictEqual(a.gaps,[{start:2,end:10,length:8},{start:12,end:20,length:8}]);
const data=L.exportData({horizon:30,abilities:[{name:'Dash',cooldown:6,duration:1,offset:0}]});
assert.strictEqual(data.abilities[0].name,'Dash');
assert.ok(L.exportText({horizon:30,abilities:[]}).includes('"coveragePercent"'));
console.log('Cooldown Weave logic: 13 assertions passed');
