const S=window.SpriteTempo,$=s=>document.querySelector(s),PINGS=[];const NS='amu-web-service-lab',SLUG='sprite-tempo';let image,playing=true,started=false,chosen='A',epoch=performance.now();
function metric(name){const img=new Image();PINGS.push(img);img.onload=img.onerror=()=>PINGS.splice(PINGS.indexOf(img),1);img.src=`https://api.counterapi.dev/v1/${NS}/${SLUG}-${name}/up?t=${Date.now()}`}
metric('view');try{if(!localStorage.getItem(`${SLUG}-counted`)){setTimeout(()=>{metric('visitor');localStorage.setItem(`${SLUG}-counted`,'1')},1200)}}catch(e){}
function demo(){const c=document.createElement('canvas');c.width=720;c.height=120;const x=c.getContext('2d');for(let i=0;i<6;i++){x.clearRect(i*120,0,120,120);x.fillStyle=['#7464dc','#6b76df','#568bdb','#45a0c9','#3aafac','#53b884'][i];x.beginPath();x.arc(i*120+60,67-Math.sin(i/6*Math.PI)*30,28,0,Math.PI*2);x.fill();x.fillStyle='#fff';x.beginPath();x.arc(i*120+50,62-Math.sin(i/6*Math.PI)*30,4,0,Math.PI*2);x.arc(i*120+70,62-Math.sin(i/6*Math.PI)*30,4,0,Math.PI*2);x.fill()}const im=new Image();im.onload=()=>{image=im};im.src=c.toDataURL()}
const ids=['columns','rows','from','to','fpsA','fpsB'];function input(){return Object.fromEntries(ids.map(id=>[id,$('#'+id).value]))}function cfg(){return S.config(input())}function markStart(){if(!started){started=true;metric('start')}}
function sync(){const c=cfg();$('#from').max=$('#to').max=c.total;$('#aVal').textContent=$('#aTag').textContent=`${c.fpsA} FPS`;$('#bVal').textContent=$('#bTag').textContent=`${c.fpsB} FPS`;$('#status').textContent=`${c.frames}コマをループ${playing?'再生中':'停止中'}`;epoch=performance.now();markStart()}
ids.forEach(id=>$('#'+id).addEventListener('input',sync));$('#file').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const url=URL.createObjectURL(f),im=new Image();im.onload=()=>{image=im;URL.revokeObjectURL(url);epoch=performance.now();markStart()};im.src=url});
$('#toggle').addEventListener('click',()=>{playing=!playing;$('#toggle').textContent=playing?'一時停止':'再生する';if(playing)epoch=performance.now();sync()});
function paint(canvas,fps,now){if(!image)return;const c=cfg(),index=S.frameAt(playing?now-epoch:0,fps,c.from,c.frames),r=S.rect(index,c.columns,c.rows,image.width,image.height),x=canvas.getContext('2d');x.clearRect(0,0,canvas.width,canvas.height);const scale=Math.min(canvas.width/r.w*.72,canvas.height/r.h*.72),w=r.w*scale,h=r.h*scale;x.imageSmoothingEnabled=false;x.drawImage(image,r.x,r.y,r.w,r.h,(canvas.width-w)/2,(canvas.height-h)/2,w,h)}
function loop(now){const c=cfg();paint($('#canvasA'),c.fpsA,now);paint($('#canvasB'),c.fpsB,now);requestAnimationFrame(loop)}
document.querySelectorAll('.choose').forEach(b=>b.addEventListener('click',()=>{chosen=b.dataset.choice;document.querySelectorAll('.choose').forEach(x=>x.classList.toggle('selected',x===b));const c=cfg(),fps=chosen==='A'?c.fpsA:c.fpsB;$('#result').hidden=false;$('#chosen').textContent=`${chosen}・${fps} FPS`;$('#detail').textContent=`${c.from}〜${c.to}コマ、1コマ約 ${(1000/fps).toFixed(1)}ms のループ設定`;metric('complete')}));
$('#download').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(S.manifest(input(),chosen),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sprite-timing.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)});demo();requestAnimationFrame(loop);
