const $=s=>document.querySelector(s),P=window.PivotPatrol,SLUG='pivot-patrol',NS='amu-web-service-lab',PINGS=[];let result=null,started=false,completed=false;const SAMPLE=`name,width,height,pivotX,pivotY
idle_01,96,112,48,18
idle_02,92,110,46,17
idle_03,98,114,51,18
idle_04,94,111,47,17
idle_05,96,113,48,18`;
function metric(n){const i=new Image;PINGS.push(i);i.onload=i.onerror=()=>PINGS.splice(PINGS.indexOf(i),1);i.src=`https://api.counterapi.dev/v1/${NS}/${SLUG}-${n}/up?t=${Date.now()}`}metric('view');try{if(!localStorage.getItem(`${SLUG}-counted`))setTimeout(()=>{metric('visitor');localStorage.setItem(`${SLUG}-counted`,'1')},1200)}catch(e){}
function draw(r){const c=$('#canvas'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.fillStyle='#0a0f17';x.fillRect(0,0,c.width,c.height);const scale=Math.min(3.4,430/Math.max(...r.items.map(i=>Math.max(i.width,i.height)))),cx=c.width/2,cy=c.height/2;x.strokeStyle='#26394a';x.beginPath();x.moveTo(cx,35);x.lineTo(cx,c.height-35);x.moveTo(35,cy);x.lineTo(c.width-35,cy);x.stroke();r.items.forEach((it,n)=>{const left=cx-it.suggestedPivotX*scale,top=cy-(it.height-it.suggestedPivotY)*scale;x.strokeStyle=`hsla(${150+n*32},65%,65%,.65)`;x.strokeRect(left,top,it.width*scale,it.height*scale);const px=left+it.pivotX*scale,py=top+(it.height-it.pivotY)*scale;x.fillStyle=it.status==='ok'?'#70dfb5':'#ff8e88';x.beginPath();x.arc(px,py,4,0,Math.PI*2);x.fill()});x.strokeStyle='#f3f5f8';x.lineWidth=2;x.beginPath();x.moveTo(cx-9,cy);x.lineTo(cx+9,cy);x.moveTo(cx,cy-9);x.lineTo(cx,cy+9);x.stroke()}
function audit(track=true){try{if(track&&!started){metric('start');started=true}result=P.audit(P.parse($('#data').value),$('#tolerance').value);$('#count').textContent=result.count;$('#flagged').textContent=result.flagged;$('#max').textContent=`${result.maxDrift} px`;$('#rows').innerHTML=result.items.map(i=>`<tr class="${i.status==='ok'?'ok':'bad'}"><td>${i.name.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}</td><td>${i.drift} px</td><td>${i.pivotX}, ${i.pivotY}</td><td>${i.suggestedPivotX}, ${i.suggestedPivotY}</td><td>${i.status==='ok'?'範囲内':'要確認'}</td></tr>`).join('');$('#results').hidden=false;$('#error').textContent='';draw(result);if(track&&!completed){metric('complete');completed=true}}catch(e){$('#error').textContent=e.message;$('#results').hidden=true}}
$('#audit').onclick=()=>audit(true);$('#sample').onclick=()=>{$('#data').value=SAMPLE;audit(true)};$('#tolerance').oninput=e=>{$('#tolOut').textContent=`${e.target.value} px`};$('#download').onclick=()=>{const payload={generated_at:new Date().toISOString(),method:'normalized median pivot; drift measured in each frame pixels',...result},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='pivot-patrol-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);$('#status').textContent='監査JSONを保存したよ。'};$('#data').value=SAMPLE;audit(false);
