const $=s=>document.querySelector(s),L=window.MotionComfortKit,SLUG='motion-comfort-kit',NS='amu-web-service-lab',PINGS=[],IDS=['distance','viewport','duration','scale','rotation','loops'];let started=false,completed=false,last=null;
function metric(n){const im=new Image;PINGS.push(im);im.onload=im.onerror=()=>PINGS.splice(PINGS.indexOf(im),1);im.src=`https://api.counterapi.dev/v1/${NS}/${SLUG}-${n}/up?t=${Date.now()}`}
metric('view');try{if(!localStorage.getItem(`${SLUG}-counted`))setTimeout(()=>{metric('visitor');localStorage.setItem(`${SLUG}-counted`,'1')},1200)}catch(e){}
function values(){return Object.fromEntries([...IDS.map(id=>[id,Number($(`#${id}`).value)]),['essential',$('#essential').checked]])}
function labels(){IDS.forEach(id=>$(`#${id}Out`).textContent=$(`#${id}`).value)}
function play(reduced=false){const v=reduced?(last||L.audit(values())).reduced:values(),o=$('#orb');o.animate([{transform:'translateX(0) scale(1) rotate(0deg)'},{transform:`translateX(${v.distance}px) scale(${1+v.scale/100}) rotate(${v.rotation}deg)`}],{duration:v.duration,easing:'ease-out',iterations:reduced?1:v.loops})}
function generate(track=true){if(track&&!started){metric('start');started=true}last=L.audit(values());const names={low:'低',medium:'中',high:'高'};$('#verdict').textContent=`動きのリスク: ${names[last.level]}`;$('#badge').textContent=last.level.toUpperCase();$('#badge').dataset.level=last.level;$('#travel').textContent=`${Math.round(last.travel*100)}%` ;$('#velocity').textContent=`${last.velocity}px/s`;$('#score').textContent=`${last.score}点`;$('#reasons').innerHTML=last.reasons.map(x=>`<li>${x}</li>`).join('');$('#action').textContent=`縮減方針: ${last.action}`;$('#css').value=L.css(values());$('#status').textContent='監査と縮減CSSの生成が完了したよ。';if(track&&!completed){metric('complete');completed=true}}
function download(){const blob=new Blob([JSON.stringify(L.report(values()),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='motion-comfort-audit.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800)}
IDS.forEach(id=>$(`#${id}`).addEventListener('input',labels));$('#sample').onclick=()=>{Object.entries({distance:220,viewport:390,duration:320,scale:18,rotation:90,loops:6}).forEach(([k,v])=>$(`#${k}`).value=v);$('#essential').checked=false;labels();generate(false)};$('#generate').onclick=()=>generate(true);$('#play').onclick=()=>play(false);$('#playReduced').onclick=()=>play(true);$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText($('#css').value);$('#status').textContent='CSSをコピーしたよ。'}catch(e){$('#css').select();$('#status').textContent='CSSを選択したよ。'}};$('#download').onclick=download;labels();generate(false);
