(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.AtlasFit=api})(typeof self!=='undefined'?self:this,function(){
  const n=v=>Number(v);
  function parse(text){const sprites=[],errors=[];String(text||'').split(/\r?\n/).forEach((line,i)=>{const raw=line.trim();if(!raw||raw.startsWith('#'))return;if(i===0&&/width|幅/i.test(raw))return;const c=raw.split(',').map(x=>x.trim()),width=n(c[0]),height=n(c[1]),count=n(c[2]),name=c[3]||`sprite-${i+1}`;if(!Number.isInteger(width)||width<1||!Number.isInteger(height)||height<1||!Number.isInteger(count)||count<1||count>5000){errors.push({line:i+1,text:raw});return}for(let k=0;k<count;k++)sprites.push({width,height,name,countIndex:k+1,line:i+1})});return{sprites,errors}}
  function pack(text,settings={}){const parsed=parse(text),size=Math.max(64,Math.floor(n(settings.size)||2048)),padding=Math.max(0,Math.floor(n(settings.padding)||0)),extrude=Math.max(0,Math.floor(n(settings.extrude)||0)),rotate=!!settings.rotate,margin=padding+extrude,pages=[],oversize=[];const items=parsed.sprites.map((s,i)=>({...s,id:i,outerW:s.width+margin*2,outerH:s.height+margin*2})).sort((a,b)=>Math.max(b.outerW,b.outerH)-Math.max(a.outerW,a.outerH)||(b.outerW*b.outerH-a.outerW*a.outerH)||a.id-b.id);
    function options(item){const list=[{w:item.outerW,h:item.outerH,rotated:false}];if(rotate&&item.outerW!==item.outerH)list.push({w:item.outerH,h:item.outerW,rotated:true});return list.filter(o=>o.w<=size&&o.h<=size)}
    items.forEach(item=>{const opts=options(item);if(!opts.length){oversize.push(item);return}let best=null;pages.forEach((page,pi)=>{page.shelves.forEach((shelf,si)=>opts.forEach(o=>{if(o.h<=shelf.height&&shelf.x+o.w<=size){const waste=(shelf.height-o.h)*o.w+(size-shelf.x-o.w)*.001;if(!best||waste<best.waste)best={pi,si,o,waste,newShelf:false}}}));opts.forEach(o=>{if(page.usedHeight+o.h<=size){const waste=(size-o.w)*o.h+o.h*.001;if(!best||waste<best.waste)best={pi,si:page.shelves.length,o,waste,newShelf:true}}})});if(!best){pages.push({shelves:[],placements:[],usedHeight:0});const o=opts.sort((a,b)=>a.h-b.h||a.w-b.w)[0];best={pi:pages.length-1,si:0,o,newShelf:true}}const page=pages[best.pi];if(best.newShelf){page.shelves.push({y:page.usedHeight,height:best.o.h,x:0});page.usedHeight+=best.o.h}const shelf=page.shelves[best.si],p={...item,page:best.pi+1,x:shelf.x+margin,y:shelf.y+margin,width:item.width,height:item.height,packedW:best.o.w,packedH:best.o.h,rotated:best.o.rotated};shelf.x+=best.o.w;page.placements.push(p)});
    const usedArea=pages.reduce((sum,p)=>sum+p.placements.reduce((a,x)=>a+x.outerW*x.outerH,0),0),capacity=pages.length*size*size,sourceArea=parsed.sprites.reduce((a,x)=>a+x.width*x.height,0);return{settings:{size,padding,extrude,rotate},errors:parsed.errors,spriteCount:parsed.sprites.length,pages,oversize,summary:{pages:pages.length,packed:parsed.sprites.length-oversize.length,oversize:oversize.length,occupancy:capacity?usedArea/capacity:0,sourceOccupancy:capacity?sourceArea/capacity:0,usedArea,sourceArea,capacity}}}
  function report(r){return{generated_at:new Date().toISOString(),algorithm:'best-fit decreasing shelf estimate; verify with target engine packer',settings:r.settings,summary:r.summary,invalid_rows:r.errors,oversize:r.oversize.map(x=>({name:x.name,width:x.width,height:x.height})),pages:r.pages.map((p,i)=>({page:i+1,used_height:p.usedHeight,placements:p.placements.map(x=>({name:x.name,index:x.countIndex,x:x.x,y:x.y,width:x.width,height:x.height,rotated:x.rotated}))}))}}
  return{parse,pack,report};
});
