(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.OnboardingPulse=api})(typeof self!=='undefined'?self:this,function(){
  const TYPES=['teach','practice','test','reward','story'];
  const round=n=>Math.round(n*10)/10;
  function parse(text){const errors=[];const beats=String(text||'').split(/\r?\n/).map((raw,i)=>({raw:raw.trim(),line:i+1})).filter(x=>x.raw&&!x.raw.startsWith('#')).map(item=>{const p=item.raw.split('|').map(x=>x.trim());const duration=Number(p[0]),type=(p[1]||'').toLowerCase();if(p.length<4||!Number.isFinite(duration)||duration<=0||!TYPES.includes(type)){errors.push({line:item.line,message:`${item.line}行目の形式を確認`});return null}return{line:item.line,duration:round(duration),type,concept:p[2]||'未分類',label:p.slice(3).join(' | ')}}).filter(Boolean);return{beats,errors}}
  function analyze(text,options={}){const parsed=parse(text),threshold=Math.max(1,Number(options.passiveThreshold)||15);let cursor=0,passiveRun=0;const warnings=[...parsed.errors],conceptMap={},timeline=[];parsed.beats.forEach((beat,index)=>{const start=cursor;cursor+=beat.duration;const active=beat.type==='practice'||beat.type==='test';passiveRun=active?0:passiveRun+beat.duration;timeline.push({...beat,index,start:round(start),end:round(cursor)});if(!conceptMap[beat.concept])conceptMap[beat.concept]={concept:beat.concept,teach:0,practice:0,test:0,reward:0,firstTeach:-1,firstTest:-1};const c=conceptMap[beat.concept];if(c[beat.type]!==undefined)c[beat.type]++;if(beat.type==='teach'&&c.firstTeach<0)c.firstTeach=index;if(beat.type==='test'&&c.firstTest<0)c.firstTest=index;if(passiveRun>threshold&&(index===parsed.beats.length-1||['practice','test'].includes(parsed.beats[index+1]?.type))){warnings.push({line:beat.line,type:'passive',message:`${round(passiveRun)}秒間、操作する区間がない`});passiveRun=0}});
    const concepts=Object.values(conceptMap).filter(c=>c.teach||c.practice||c.test).map(c=>{let status='covered';if(c.test&&(!c.teach||c.firstTest<c.firstTeach)){status='test-first';warnings.push({type:'order',message:`「${c.concept}」は説明より先に確認される`})}else if(c.teach&&!c.practice&&!c.test){status='unverified';warnings.push({type:'coverage',message:`「${c.concept}」は説明後の練習・確認がない`})}else if(c.teach&&!c.test){status='practice-only';warnings.push({type:'coverage',message:`「${c.concept}」は練習のみで確認区間がない`})}return{...c,status}});
    for(let i=0;i<timeline.length-2;i++){if(timeline.slice(i,i+3).every(x=>x.type==='teach'))warnings.push({type:'overload',line:timeline[i].line,message:'説明が3項目連続している'});}
    const activeSeconds=parsed.beats.filter(x=>['practice','test'].includes(x.type)).reduce((a,b)=>a+b.duration,0),teachable=concepts.filter(x=>x.teach).length,covered=concepts.filter(x=>x.teach&&x.test&&x.firstTest>x.firstTeach).length;
    return{summary:{totalSeconds:round(cursor),activeSeconds:round(activeSeconds),activeRatio:cursor?round(activeSeconds/cursor):0,teachable,covered,coverage:teachable?round(covered/teachable):0,issueCount:warnings.length},timeline,concepts,warnings,options:{passiveThreshold:threshold}}}
  function exportText(text,options){return JSON.stringify({format:'onboarding-pulse/v1',source:text,analysis:analyze(text,options)},null,2)}
  return{TYPES,parse,analyze,exportText};
});
