(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.LocaleGuard=api})(typeof self!=='undefined'?self:this,function(){
  function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;const src=String(text||'').replace(/^\uFEFF/,'');for(let i=0;i<src.length;i++){const c=src[i];if(quoted){if(c==='"'&&src[i+1]==='"'){cell+='"';i++}else if(c==='"')quoted=false;else cell+=c}else if(c==='"')quoted=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell.replace(/\r$/,''));rows.push(row)}return{rows,error:quoted?'引用符が閉じていないセルがある':''}}
  function tokens(value){const found=String(value||'').match(/\{[\w.-]+\}|%(?:\d+\$)?[sdif]|\$\([\w.-]+\)/g)||[];return[...new Set(found)].sort()}
  function same(a,b){return a.length===b.length&&a.every((x,i)=>x===b[i])}
  function audit(text){const parsed=parseCSV(text),issues=[];if(parsed.error)issues.push({level:'error',row:0,key:'CSV',locale:'—',message:parsed.error});if(!parsed.rows.length)return{headers:[],entries:[],issues,summary:{rows:0,locales:0,errors:issues.length,warnings:0,coverage:0}};const headers=parsed.rows[0].map(x=>x.trim()),locales=headers.slice(1),entries=[],seen=new Map();if(headers[0]!=='key')issues.push({level:'error',row:1,key:'header',locale:headers[0]||'空欄',message:'先頭列は key にしてね'});if(locales.length<1)issues.push({level:'error',row:1,key:'header',locale:'—',message:'言語列がない'});const localeSeen=new Set();locales.forEach((l,i)=>{if(!l||localeSeen.has(l.toLowerCase()))issues.push({level:'error',row:1,key:'header',locale:l||`列${i+2}`,message:'言語名が空欄または重複'});localeSeen.add(l.toLowerCase())});
    parsed.rows.slice(1).forEach((raw,index)=>{if(raw.every(x=>!x.trim()))return;const row=index+2,key=(raw[0]||'').trim(),values=locales.map((_,i)=>raw[i+1]??'');entries.push({row,key,values});if(!key)issues.push({level:'error',row,key:'(空欄)',locale:'key',message:'キーが空欄'});else if(seen.has(key))issues.push({level:'error',row,key,locale:'key',message:`キーが重複（先出 ${seen.get(key)}行）`});else seen.set(key,row);if(raw.length>headers.length)issues.push({level:'warn',row,key:key||'(空欄)',locale:'—',message:'ヘッダーよりセルが多い'});const base=tokens(values[0]);values.forEach((value,i)=>{const locale=locales[i]||`列${i+2}`;if(!value.trim())issues.push({level:'error',row,key:key||'(空欄)',locale,message:'翻訳が空欄'});else if(i>0&&!same(base,tokens(value)))issues.push({level:'error',row,key:key||'(空欄)',locale,message:`プレースホルダー不一致（基準: ${base.join(' ')||'なし'} / 対象: ${tokens(value).join(' ')||'なし'}）`});if(i>0&&values[0].length>=4&&value.length/values[0].length>=2.2)issues.push({level:'warn',row,key:key||'(空欄)',locale,message:`基準文の${(value.length/values[0].length).toFixed(1)}倍。UI幅を確認`})})});
    const errors=issues.filter(x=>x.level==='error').length,warnings=issues.length-errors,total=entries.length*locales.length,filled=entries.reduce((n,e)=>n+e.values.filter(v=>v.trim()).length,0);return{headers,locales,entries,issues,summary:{rows:entries.length,locales:locales.length,errors,warnings,coverage:total?filled/total:0}}}
  function escapeCSV(value){const s=String(value??'');return/[",\n\r]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
  function normalizedCSV(report){return[report.headers,...report.entries.map(e=>[e.key,...e.values])].map(r=>r.map(escapeCSV).join(',')).join('\n')}
  function exportReport(report){return{generated_at:new Date().toISOString(),summary:report.summary,locales:report.locales,issues:report.issues}}
  return{parseCSV,tokens,audit,escapeCSV,normalizedCSV,exportReport};
});
