const $=s=>document.querySelector(s),T=window.TextureBudgetLens,SLUG='texture-budget-lens',NS='amu-web-service-lab',PINGS=[];let source=document.createElement('canvas'),report=null,started=false,completed=false;
function metric(name){const image=new Image;PINGS.push(image);image.onload=image.onerror=()=>PINGS.splice(PINGS.indexOf(image),1);image.src=`https://api.counterapi.dev/v1/${NS}/${SLUG}-${name}/up?t=${Date.now()}`}
metric('view');try{if(!localStorage.getItem(`${SLUG}-counted`))setTimeout(()=>{metric('visitor');localStorage.setItem(`${SLUG}-counted`,'1')},1200)}catch(e){}
function sample(){source.width=1600;source.height=900;const c=source.getContext('2d'),g=c.createLinearGradient(0,0,1600,900);g.addColorStop(0,'#122c4c');g.addColorStop(.55,'#244f5a');g.addColorStop(1,'#6f3f57');c.fillStyle=g;c.fillRect(0,0,1600,900);for(let y=0;y<900;y+=45)for(let x=0;x<1600;x+=45){c.fillStyle=(x/45+y/45)%2?'rgba(255,255,255,.07)':'rgba(0,0,0,.08)';c.fillRect(x,y,45,45)}c.strokeStyle='#a8e8ff';c.lineWidth=8;for(let i=0;i<14;i++){c.beginPath();c.arc(800,450,36+i*27,0,Math.PI*2);c.stroke()}c.fillStyle='#f7d59a';c.font='700 116px system-ui';c.textAlign='center';c.fillText('TEXTURE',800,425);c.font='500 38px system-ui';c.fillText('fine lines · type · gradients',800,500);c.fillStyle='#fff';for(let i=0;i<120;i++){const x=(i*137)%1550+25,y=(i*71)%850+25;c.fillRect(x,y,2+(i%3),2+(i%3))}}
function grayFromCanvas(canvas,w=320,h=180){const tmp=document.createElement('canvas');tmp.width=w;tmp.height=h;const c=tmp.getContext('2d',{willReadFrequently:true});c.drawImage(canvas,0,0,w,h);const d=c.getImageData(0,0,w,h).data,g=new Uint8Array(w*h);for(let i=0;i<g.length;i++)g[i]=Math.round(d[i*4]*.2126+d[i*4+1]*.7152+d[i*4+2]*.0722);return g}
function formatBytes(bytes){return bytes<1048576?`${(bytes/1024).toFixed(1)} KiB`:`${(bytes/1048576).toFixed(2)} MiB`}
function analyze(track=true){try{if(!source.width)throw new Error('画像を選んでね');if(track&&!started){metric('start');started=true}const format=$('#format').value,mipmaps=$('#mipmaps').checked,plans=T.plan(source.width,source.height,[2048,1024,512,256],format,mipmaps),baseEnergy=T.gradientEnergy(grayFromCanvas(source),320,180);const cards=[];report={generated_at:new Date().toISOString(),source:{width:source.width,height:source.height},format,mipmaps,variants:[]};plans.forEach((p,index)=>{const reduced=document.createElement('canvas');reduced.width=p.width;reduced.height=p.height;const rc=reduced.getContext('2d');rc.imageSmoothingEnabled=true;rc.imageSmoothingQuality='high';rc.drawImage(source,0,0,p.width,p.height);const evalCanvas=document.createElement('canvas');evalCanvas.width=320;evalCanvas.height=180;const ec=evalCanvas.getContext('2d');ec.imageSmoothingEnabled=true;ec.imageSmoothingQuality='high';ec.drawImage(reduced,0,0,320,180);const energy=T.gradientEnergy(grayFromCanvas(evalCanvas),320,180),detail=baseEnergy?Math.min(100,energy/baseEnergy*100):100,preview=document.createElement('canvas');preview.width=640;preview.height=360;preview.getContext('2d').drawImage(reduced,0,0,640,360);const variant={...p,detailRetention:Number(detail.toFixed(1))};report.variants.push(variant);const card=document.createElement('article');card.className='card';card.innerHTML=`<div class="preview"></div><div class="card-body"><div class="card-head"><h3>Max ${p.maxSize}</h3><span class="size">${p.width} × ${p.height}</span></div><div class="stats"><div class="stat"><small>GPU概算</small><strong>${formatBytes(p.bytes)}</strong></div><div class="stat"><small>細部保持率</small><strong>${detail.toFixed(1)}%</strong></div></div><div class="bar"><span style="width:${detail.toFixed(1)}%"></span></div></div>`;card.querySelector('.preview').appendChild(preview);cards.push(card)});$('#cards').replaceChildren(...cards);$('#sourceSize').textContent=`${source.width} × ${source.height}`;$('#error').textContent='';if(track&&!completed){metric('complete');completed=true}}catch(e){$('#error').textContent=e.message}}
$('#sample').onclick=()=>{sample();analyze(true)};$('#analyze').onclick=()=>analyze(true);$('#format').onchange=()=>analyze(false);$('#mipmaps').onchange=()=>analyze(false);$('#file').onchange=e=>{const file=e.target.files[0];if(!file)return;const image=new Image;image.onload=()=>{source.width=image.naturalWidth;source.height=image.naturalHeight;source.getContext('2d').drawImage(image,0,0);URL.revokeObjectURL(image.src);analyze(true)};image.onerror=()=>{$('#error').textContent='画像を読み込めなかった'};image.src=URL.createObjectURL(file)};
$('#download').onclick=()=>{if(!report)return;const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='texture-budget-comparison.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);$('#status').textContent='比較JSONを保存したよ。'};sample();analyze(false);
