(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.PoolPressure=api})(typeof self!=='undefined'?self:this,function(){
  const num=v=>{const n=Number(v);return Number.isFinite(n)?n:NaN};
  function parse(text){const waves=[],errors=[];String(text||'').split(/\r?\n/).forEach((line,i)=>{const raw=line.trim();if(!raw||raw.startsWith('#'))return;if(i===0&&/start|開始/i.test(raw))return;const c=raw.split(',').map(v=>v.trim()),start=num(c[0]),duration=num(c[1]),rate=num(c[2]),lifetime=num(c[3]),burst=num(c[4]),name=c[5]||`wave-${i+1}`;if(!(start>=0)||!(duration>=0)||!(rate>=0)||!(lifetime>0)||!(burst>=0)||!Number.isInteger(burst)){errors.push({line:i+1,text:raw});return}waves.push({start,duration,rate,lifetime,burst,name,line:i+1})});return{waves,errors}}
  function expand(waves){const events=[];waves.forEach((w,wi)=>{for(let i=0;i<w.burst;i++)events.push({time:w.start,end:w.start+w.lifetime,name:w.name,wave:wi,kind:'burst'});if(w.rate>0)for(let n=1;;n++){const time=w.start+n/w.rate;if(time>=w.start+w.duration-1e-9)break;events.push({time,end:time+w.lifetime,name:w.name,wave:wi,kind:'rate'})}});return events.sort((a,b)=>a.time-b.time||a.end-b.end||a.wave-b.wave)}
  function demandTimeline(events){const map=new Map;events.forEach(e=>{if(!map.has(e.time))map.set(e.time,{add:0,remove:0});map.get(e.time).add++;if(!map.has(e.end))map.set(e.end,{add:0,remove:0});map.get(e.end).remove++});let active=0,peak=0,peakAt=0;const points=[...map.entries()].sort((a,b)=>a[0]-b[0]).map(([time,d])=>{active-=d.remove;active+=d.add;if(active>peak){peak=active;peakAt=time}return{time,active}});return{points,peak,peakAt}}
  function analyze(text,settings={}){const parsed=parse(text),events=expand(parsed.waves),poolSize=Math.max(1,Math.floor(num(settings.poolSize)||32)),headroom=Math.max(0,num(settings.headroom)||0),active=[],overflow=[];events.forEach(e=>{for(let i=active.length-1;i>=0;i--)if(active[i].end<=e.time)active.splice(i,1);if(active.length>=poolSize)overflow.push(e);else active.push(e)});const demand=demandTimeline(events),byWave=parsed.waves.map((w,i)=>{const list=events.filter(e=>e.wave===i);return{name:w.name,generated:list.length,burst:w.burst,lifetime:w.lifetime}}),recommended=Math.max(1,Math.ceil(demand.peak*(1+headroom/100)));return{waves:parsed.waves,errors:parsed.errors,events,overflow,byWave,demand,settings:{poolSize,headroom},summary:{generated:events.length,peak:demand.peak,peakAt:demand.peakAt,overflow:overflow.length,overflowRate:events.length?overflow.length/events.length:0,recommended}}}
  function report(r){return{generated_at:new Date().toISOString(),assumptions:r.settings,summary:r.summary,waves:r.waves,per_wave:r.byWave,overflow_samples:r.overflow.slice(0,100).map(e=>({time:e.time,name:e.name,release_at:e.end}))}}
  return{parse,expand,demandTimeline,analyze,report};
});
