(function(root){'use strict';
function parse(text){const rows=String(text??'').trim().split(/\r?\n/).filter(Boolean).map((line,i)=>{const p=line.trim().split(/[\s,;]+/).map(Number);if(p.length!==4||p.some(v=>!Number.isFinite(v)))throw new Error(`${i+1}行目は time,x,y,z の4数値で入力してね`);return{t:p[0],x:p[1],y:p[2],z:p[3]}});if(rows.length<3)throw new Error('3行以上のTransformサンプルを入力してね');for(let i=1;i<rows.length;i++)if(rows[i].t<=rows[i-1].t)throw new Error('timeは重複なしの昇順にしてね');return rows}
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z);
function lerp(a,b,t){const u=(t-a.t)/(b.t-a.t);return{x:a.x+(b.x-a.x)*u,y:a.y+(b.y-a.y)*u,z:a.z+(b.z-a.z)*u}}
function simplify(points,tolerance){tolerance=Number(tolerance);if(!Number.isFinite(tolerance)||tolerance<=0)throw new Error('許容誤差は0より大きい値にしてね');const keep=new Set([0,points.length-1]),stack=[[0,points.length-1]];while(stack.length){const[a,b]=stack.pop();let max=-1,index=-1;for(let i=a+1;i<b;i++){const e=dist(points[i],lerp(points[a],points[b],points[i].t));if(e>max){max=e;index=i}}if(max>tolerance){keep.add(index);stack.push([a,index],[index,b])}}return[...keep].sort((a,b)=>a-b).map(i=>points[i])}
function sample(keys,t){let hi=keys.findIndex(k=>k.t>=t);if(hi<0)return keys[keys.length-1];if(hi===0)return keys[0];return lerp(keys[hi-1],keys[hi],t)}
function analyze(input){const points=Array.isArray(input.points)?input.points:parse(input.text),tolerance=Number(input.tolerance),keys=simplify(points,tolerance),errors=points.map(p=>dist(p,sample(keys,p.t))),maxError=Math.max(...errors),rmsError=Math.sqrt(errors.reduce((s,e)=>s+e*e,0)/errors.length),removed=points.length-keys.length,reduction=removed/points.length;let peakIndex=errors.indexOf(maxError);const verdict=reduction>=.7?'削減余地が大きい':reduction>=.35?'削減候補あり':'元キーを維持推奨';const actions=[];if(reduction>=.35)actions.push(`${removed}キーを削減しても位置誤差は許容値内。対象クリップの見た目と接地を実機確認`);if(peakIndex>0&&peakIndex<points.length-1)actions.push(`最大誤差は ${points[peakIndex].t.toFixed(3)} s。急加速・接触・方向転換がないか確認`);if(reduction<.35)actions.push('曲率変化が多い区間。許容誤差を増やす前に、動きの重要度とカメラ距離を確認');actions.push('回転・スケール・補間方式・エンジン固有圧縮は別途確認');return{tolerance,sourceCount:points.length,keyCount:keys.length,removed,reduction,maxError,rmsError,duration:points[points.length-1].t-points[0].t,peakTime:points[peakIndex].t,verdict,actions,points,keys,errors}}
function csv(keys){return'time,x,y,z\n'+keys.map(k=>[k.t,k.x,k.y,k.z].join(',')).join('\n')+'\n'}
root.TransformKeySieve={parse,dist,lerp,simplify,sample,analyze,csv};})(typeof window!=='undefined'?window:globalThis);
