const $=s=>document.querySelector(s),E=window.EconomyTide,SLUG='economy-tide',NS='amu-web-service-lab',PINGS=[];let started=false,completed=false,lastResult=null,nextId=1;
function metric(name){const img=new Image();PINGS.push(img);img.onload=img.onerror=()=>PINGS.splice(PINGS.indexOf(img),1);img.src=`https://api.counterapi.dev/v1/${NS}/${SLUG}-${name}/up?t=${Date.now()}`}
metric('view');try{if(!localStorage.getItem(`${SLUG}-counted`)){setTimeout(()=>{metric('visitor');localStorage.setItem(`${SLUG}-counted`,'1')},1200)}}catch(e){}
function begin(){if(!started){started=true;metric('start')}}function finish(){if(!completed){completed=true;metric('complete')}}
const defaults=[{label:'クエスト報酬',type:'source',amount:120,from:1,to:30,every:1},{label:'ログイン報酬',type:'source',amount:20,from:1,to:30,every:1},{label:'消耗品',type:'sink',amount:35,from:1,to:30,every:1},{label:'装備強化',type:'sink',amount:300,from:3,to:30,every:3}];
function addRow(data={label:'新しい項目',type:'sink',amount:100,from:1,to:Number($('#sessions').value)||30,every:1}){const row=$('#rowTemplate').content.firstElementChild.cloneNode(true);row.dataset.id=`item-${nextId++}`;Object.entries(data).forEach(([key,value])=>{const input=row.querySelector(`[data-key="${key}"]`);if(input)input.value=value});row.querySelector('.remove').addEventListener('click',()=>{begin();row.remove();render()});row.querySelectorAll('input,select').forEach(input=>input.addEventListener('input',()=>{begin();render()}));$('#rows').append(row)}
function readConfig(){return{initialBalance:$('#initial').value,sessions:$('#sessions').value,events:[...$('#rows').children].map(row=>{const event={id:row.dataset.id};row.querySelectorAll('[data-key]').forEach(input=>event[input.dataset.key]=input.value);return event})}}
const yen=n=>Math.round(n).toLocaleString('ja-JP');
function draw(result){const canvas=$('#chart'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,p={l:62,r:24,t:30,b:45},values=[result.config.initialBalance,...result.timeline.map(x=>x.balance),0],min=Math.min(...values),max=Math.max(...values),range=max-min||1,x=i=>p.l+i*(w-p.l-p.r)/result.config.sessions,y=v=>p.t+(max-v)*(h-p.t-p.b)/range;ctx.clearRect(0,0,w,h);ctx.font='12px system-ui';ctx.fillStyle='#789087';ctx.strokeStyle='#263b35';ctx.lineWidth=1;for(let i=0;i<=4;i++){const value=min+range*i/4,py=y(value);ctx.beginPath();ctx.moveTo(p.l,py);ctx.lineTo(w-p.r,py);ctx.stroke();ctx.fillText(yen(value),8,py+4)}if(min<0&&max>0){ctx.strokeStyle='#ef6c7377';ctx.beginPath();ctx.moveTo(p.l,y(0));ctx.lineTo(w-p.r,y(0));ctx.stroke()}const gradient=ctx.createLinearGradient(0,p.t,0,h-p.b);gradient.addColorStop(0,'#65d6b466');gradient.addColorStop(1,'#65d6b405');ctx.beginPath();ctx.moveTo(x(0),y(result.config.initialBalance));result.timeline.forEach(item=>ctx.lineTo(x(item.session),y(item.balance)));ctx.lineTo(x(result.config.sessions),h-p.b);ctx.lineTo(x(0),h-p.b);ctx.closePath();ctx.fillStyle=gradient;ctx.fill();ctx.beginPath();ctx.moveTo(x(0),y(result.config.initialBalance));result.timeline.forEach(item=>ctx.lineTo(x(item.session),y(item.balance)));ctx.strokeStyle=result.summary.firstNegative?'#ef6c73':'#65d6b4';ctx.lineWidth=4;ctx.stroke();ctx.fillStyle='#8ba198';ctx.textAlign='center';[1,Math.ceil(result.config.sessions/2),result.config.sessions].forEach(s=>ctx.fillText(`S${s}`,x(s),h-16));ctx.textAlign='left'}
function render(){lastResult=E.simulate(readConfig());const s=lastResult.summary;$('#final').textContent=yen(s.finalBalance);$('#coverage').textContent=Number.isFinite(s.coverage)?`${Math.round(s.coverage*100)}%`:'∞';$('#minimum').textContent=yen(s.minBalance);draw(lastResult);const d=$('#diagnosis');d.className='diagnosis'+(s.status==='shortage'?' bad':s.status==='balanced'?'':' warn');const detail=`総流入 ${yen(s.totalSource)} ／ 総流出 ${yen(s.totalSink)} ／ 純増減 ${s.net>=0?'+':''}${yen(s.net)}`;d.innerHTML=`<strong>${s.message}</strong><br>${detail}`}
$('#add').addEventListener('click',()=>{begin();addRow();render()});$('#run').addEventListener('click',()=>{begin();render();$('#diagnosis').scrollIntoView({behavior:'smooth',block:'center'})});$('#initial').addEventListener('input',()=>{begin();render()});$('#sessions').addEventListener('input',()=>{begin();render()});$('#copy').addEventListener('click',()=>{begin();const text=E.exportText(readConfig()),area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();let copied=false;try{copied=document.execCommand('copy')}catch(e){}area.remove();$('#copyStatus').textContent=copied?'試算JSONをコピーしたよ。':'試算JSONを生成したよ。';finish()});defaults.forEach(addRow);render();
