(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.WaveLoom=api})(this,function(){
  const TYPES=[{id:'grunt',threat:1,color:'#b8f35a'},{id:'ranger',threat:1.6,color:'#51d9d0'},{id:'brute',threat:3,color:'#ff9866'}];
  const clamp=(v,min,max)=>Math.min(max,Math.max(min,Number.isFinite(Number(v))?Number(v):min));
  const round=(v,d=1)=>{const p=10**d;return Math.round((Number(v)+Number.EPSILON)*p)/p};
  function normalize(input={}){return{duration:round(clamp(input.duration,30,180)),waves:Math.round(clamp(input.waves,2,10)),rest:round(clamp(input.rest,0,15)),ramp:round(clamp(input.ramp,80,260)),mix:{grunt:clamp(input.mix&&input.mix.grunt,0,10),ranger:clamp(input.mix&&input.mix.ranger,0,10),brute:clamp(input.mix&&input.mix.brute,0,10)}}}
  function allocate(total,mix){let weights=TYPES.map(t=>Math.max(0,Number(mix[t.id])||0)),sum=weights.reduce((a,b)=>a+b,0);if(!sum){weights=[1,0,0];sum=1}const raw=weights.map(w=>total*w/sum),counts=raw.map(Math.floor);let left=total-counts.reduce((a,b)=>a+b,0);raw.map((v,i)=>({i,f:v-Math.floor(v)})).sort((a,b)=>b.f-a.f).slice(0,left).forEach(x=>counts[x.i]++);return Object.fromEntries(TYPES.map((t,i)=>[t.id,counts[i]]))}
  function analyze(input={}){const n=normalize(input),totalRest=n.rest*(n.waves-1),active=Math.max(n.waves,n.duration-totalRest),waveLength=active/n.waves,rows=[];let cursor=0;for(let i=0;i<n.waves;i++){const progress=n.waves===1?0:i/(n.waves-1),intensity=1+(n.ramp/100-1)*progress,count=Math.max(1,Math.round(4*intensity)),mix=allocate(count,n.mix),threat=round(TYPES.reduce((s,t)=>s+mix[t.id]*t.threat,0));rows.push({index:i+1,start:round(cursor),end:round(cursor+waveLength),count,mix,threat});cursor+=waveLength+(i<n.waves-1?n.rest:0)}const total=rows.reduce((s,w)=>s+w.count,0),peak=Math.max(...rows.map(w=>w.threat)),restRatio=round(totalRest/n.duration*100),curve=rows.map(w=>({time:round((w.start+w.end)/2),threat:w.threat}));let status='balanced';if(restRatio<8)status='relentless';else if(restRatio>35)status='fragmented';return{...n,totalRest:round(totalRest),waveLength:round(waveLength),total,peak,restRatio,rows,curve,status}}
  function exportData(input={}){const a=analyze(input);return{durationSeconds:a.duration,restSeconds:a.rest,rampPercent:a.ramp,totalEnemies:a.total,peakThreat:a.peak,waves:a.rows,note:'Threat weights: grunt 1, ranger 1.6, brute 3. Spawns are evenly distributed inside each wave.'}}
  const exportText=input=>JSON.stringify(exportData(input),null,2);
  return{TYPES,clamp,round,normalize,allocate,analyze,exportData,exportText};
});