const $=s=>document.querySelector(s),L=window.NormalMapCompass,SLUG='normal-map-compass',NS='amu-web-service-lab',PINGS=[];let source=null,result=null,name='normal-sample',started=false,completed=false;
function metric(n){const im=new Image;PINGS.push(im);im.onload=im.onerror=()=>PINGS.splice(PINGS.indexOf(im),1);im.src=`https://api.counterapi.dev/v1/${NS}/${SLUG}-${n}/up?t=${Date.now()}`}
metric('view');try{if(!localStorage.getItem(`${SLUG}-counted`))setTimeout(()=>{metric('visitor');localStorage.setItem(`${SLUG}-counted`,'1')},1200)}catch(e){}
function canvasData(canvas,data,w,h){canvas.width=w;canvas.height=h;canvas.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(data),w,h),0,0)}
function sample(){const w=320,h=320,d=new Uint8ClampedArray(w*h*4);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const o=(y*w+x)*4,nx=(x-w/2)/(w*.36),ny=(y-h/2)/(h*.36),r=Math.hypot(nx,ny);let vx=0,vy=0,vz=1;if(r<1){const z=Math.sqrt(Math.max(0,1-r*r));vx=nx;vy=ny;vz=z}if(x>245&&x<280&&y>35&&y<70){vx=.7;vy=.7;vz=.05}const len=Math.hypot(vx,vy,vz)||1;d[o]=Math.round((vx/len+1)*127.5);d[o+1]=Math.round((vy/len+1)*127.5);d[o+2]=Math.round((vz/len+1)*127.5);d[o+3]=255}setSource(d,w,h,'generated-dome-normal.png')}
function setSource(data,w,h,label){source={data:new Uint8ClampedArray(data),width:w,height:h};name=label.replace(/\.[^.]+$/,'')||'normal';$('#fileName').textContent=`${label} ・ ${w}×${h}`;canvasData($('#normal'),source.data,w,h);result=null;$('#summary').textContent='解析待ち';$('#score').textContent='—';$('#json').disabled=$('#png').disabled=true;render()}
function render(){if(!source)return;const a=Number($('#angle').value);$('#angleText').textContent=a+'°';canvasData($('#before'),L.shade(source.data,source.width,source.height,a,false),source.width,source.height);canvasData($('#after'),L.shade(source.data,source.width,source.height,a,true),source.width,source.height)}
function analyze(track=true){try{if(!source)throw new Error('画像を選んでね');if(track&&!started){metric('start');started=true}result={...L.analyze(source.data,source.width,source.height),width:source.width,height:source.height};$('#summary').textContent=result.grade;$('#score').textContent=(100-result.invalidRate*100).toFixed(1);$('#invalid').textContent=(result.invalidRate*100).toFixed(2)+'%';$('#back').textContent=(result.backRate*100).toFixed(2)+'%';$('#flat').textContent=(result.flatRate*100).toFixed(1)+'%';$('#json').disabled=$('#png').disabled=false;$('#error').textContent='';$('#status').textContent=`${result.pixels.toLocaleString()}画素を端末内で監査したよ。`;if(track&&!completed){metric('complete');completed=true}}catch(e){$('#error').textContent=e.message}}
function load(file){if(!file)return;const im=new Image,url=URL.createObjectURL(file);im.onload=()=>{const c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(im,0,0);setSource(g.getImageData(0,0,c.width,c.height).data,c.width,c.height,file.name);URL.revokeObjectURL(url)};im.onerror=()=>{$('#error').textContent='画像を読み込めなかった';URL.revokeObjectURL(url)};im.src=url}
function download(blob,file){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=file;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800)}
function saveJson(){if(!result)return;const data=L.report(result,name,$('#flip').checked);download(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),`${name}-normal-audit.json`)}
function savePng(){if(!source)return;const d=$('#flip').checked?L.flipGreen(source.data):source.data,c=document.createElement('canvas');canvasData(c,d,source.width,source.height);c.toBlob(b=>download(b,`${name}${$('#flip').checked?'-green-flipped':''}.png`),'image/png');$('#status').textContent=$('#flip').checked?'Green反転PNGを保存したよ。':'元チャンネルのPNGを保存したよ。'}
$('#sample').onclick=()=>{sample();analyze(true)};$('#file').onchange=e=>load(e.target.files[0]);$('#analyze').onclick=()=>analyze(true);$('#angle').oninput=render;$('#json').onclick=saveJson;$('#png').onclick=savePng;sample();analyze(false);
