(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.NormalMapCompass=api})(typeof self!=='undefined'?self:this,function(){
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  function decode(r,g,b,flipY=false){let x=r/127.5-1,y=g/127.5-1,z=b/127.5-1;if(flipY)y=-y;return{x,y,z,length:Math.hypot(x,y,z)}}
  function analyze(data,width,height){if(!data||!width||!height||data.length<width*height*4)throw new Error('画像データが不正');let count=0,invalid=0,back=0,flat=0,sx=0,sy=0,sz=0,min=Infinity,max=0;for(let i=0;i<width*height;i++){if(data[i*4+3]===0)continue;const n=decode(data[i*4],data[i*4+1],data[i*4+2]);count++;sx+=n.x;sy+=n.y;sz+=n.z;min=Math.min(min,n.length);max=Math.max(max,n.length);if(Math.abs(n.length-1)>.12)invalid++;if(n.z<0)back++;if(Math.abs(n.x)<.04&&Math.abs(n.y)<.04&&n.z>.9)flat++}if(!count)throw new Error('不透明な画素がない');return{pixels:count,invalid,invalidRate:invalid/count,back,backRate:back/count,flat,flatRate:flat/count,mean:{x:sx/count,y:sy/count,z:sz/count},minLength:min,maxLength:max,grade:invalid/count<.01&&back/count<.001?'良好':invalid/count<.08&&back/count<.01?'要確認':'修正推奨'}}
  function shade(data,width,height,angle=315,flipY=false){const out=new Uint8ClampedArray(data.length),a=angle*Math.PI/180,lx=Math.cos(a)*.65,ly=Math.sin(a)*.65,lz=Math.sqrt(1-lx*lx-ly*ly);for(let i=0;i<width*height;i++){const o=i*4,n=decode(data[o],data[o+1],data[o+2],flipY),len=n.length||1,d=Math.max(0,(n.x*lx+n.y*ly+n.z*lz)/len),v=Math.round(clamp(32+d*223,0,255));out[o]=Math.round(v*.88);out[o+1]=Math.round(v*.96);out[o+2]=v;out[o+3]=data[o+3]}return out}
  function flipGreen(data){const out=new Uint8ClampedArray(data);for(let i=0;i<out.length;i+=4)out[i+1]=255-out[i+1];return out}
  function report(result,name,flipped){return{tool:'Normal Map Compass',file:name,width:result.width,height:result.height,green_channel:flipped?'flipped for export':'unchanged',opaque_pixels:result.pixels,invalid_vector_rate:Number((result.invalidRate*100).toFixed(2)),backward_normal_rate:Number((result.backRate*100).toFixed(2)),flat_pixel_rate:Number((result.flatRate*100).toFixed(2)),mean_normal:Object.fromEntries(Object.entries(result.mean).map(([k,v])=>[k,Number(v.toFixed(4))])),vector_length:{min:Number(result.minLength.toFixed(4)),max:Number(result.maxLength.toFixed(4))},grade:result.grade,note:'Y方向の正解は元画像だけでは断定できないため、照明プレビューで確認してください。'}}
  return{decode,analyze,shade,flipGreen,report};
});
