const $=s=>document.querySelector(s),L=window.FrameBudgetLab,SLUG='frame-budget-lab',NS='amu-web-service-lab',PINGS=[],KEYS=[...L.CPU_KEYS,'gpu'];let started=false,completed=false;
function metric(name){const img=new Image();PINGS.push(img);img.onload=img.onerror=()=>PINGS.splice(PINGS.indexOf(img),1);img.src=`https://api.counterapi.dev/v1/${NS}/${SLUG}-${name}/up?t=${Date.now()}`}
metric('view');try{if(!localStorage.getItem(`${SLUG}-counted`)){setTimeout(()=>{metric('visitor');localStorage.setItem(`${SLUG}-counted`,'1')},1200)}}catch(e){}
function begin(){if(!started){started=true;metric('start')}}function finish(){if(!completed){completed=true;metric('complete')}}
const PRESETS={balanced:{fps:60,gameplay:2.5,physics:1.5,animation:1,renderCpu:3,otherCpu:2,gpu:12},mobile:{fps:60,gameplay:3,physics:2,animation:1.5,renderCpu:3.5,otherCpu:2.5,gpu:15},high:{fps:120,gameplay:1.4,physics:.8,animation:.6,renderCpu:2,otherCpu:1,gpu:7.2}};
function values(){const v={fps:$('#fps').value};for(const k of KEYS)v[k]=$('#'+k).value;return v}
function render(){const a=L.analyze(values()),scale=Math.max(a.budget*1.2,a.cpu,a.gpu,.1);$('#budget').textContent=a.budget.toFixed(2)+' ms';$('#frame').textContent=a.frame.toFixed(1)+' ms';$('#headroom').textContent=(a.headroom>0?'+':'')+a.headroom.toFixed(2)+' ms';$('#bottleneck').textContent=a.bottleneck==='balanced'?'均衡':a.bottleneck.toUpperCase();$('#cpuBar').style.width=Math.min(100,a.cpu/scale*100)+'%';$('#gpuBar').style.width=Math.min(100,a.gpu/scale*100)+'%';$('#cpuBar').innerHTML=`<span>CPU ${a.cpu.toFixed(1)} ms</span>`;$('#gpuBar').innerHTML=`<span>GPU ${a.gpu.toFixed(1)} ms</span>`;document.querySelector('.tick').style.left=(a.budget/scale*100)+'%';for(const k of KEYS)$('#'+k+'Out').value=a[k].toFixed(1)+' ms';const text=a.status==='safe'?`予算内。${a.headroom.toFixed(2)} msの余裕を想定できる。`:a.status==='tight'?`予算内だが余裕は${a.headroom.toFixed(2)} ms。実機の変動を吸収しにくい。`:`予算を${Math.abs(a.headroom).toFixed(2)} ms超過。${a.bottleneck==='cpu'?'CPU内訳':'GPU時間'}の削減が必要。`;$('#verdict').textContent=text;$('#verdict').className='verdict '+a.status}
function apply(p){$('#fps').value=p.fps;for(const k of KEYS)$('#'+k).value=p[k];render()}
$('#fps').addEventListener('change',()=>{begin();render()});for(const k of KEYS)$('#'+k).addEventListener('input',()=>{begin();render()});document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{begin();apply(PRESETS[b.dataset.preset])}));$('#copy').addEventListener('click',()=>{begin();const text=L.exportText(values()),output=$('#jsonOutput');output.textContent=text;output.hidden=false;const area=document.createElement('textarea');area.value=text;area.setAttribute('readonly','');area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();const copied=document.execCommand('copy');area.remove();$('#copyStatus').textContent=copied?'設計JSONを表示し、コピーしたよ。':'設計JSONを表示したよ。';finish()});render();
