(function(root){
'use strict';
const round=(n,d=2)=>Number(n.toFixed(d));
function positive(v,label,allowZero=false){const n=Number(v);if(!Number.isFinite(n)||(allowZero?n<0:n<=0))throw new Error(`${label}は${allowZero?'0以上':'0より大きい'}の数値にしてね`);return n}
function parseSources(text){const rows=String(text||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map((line,i)=>{const p=line.split(/[,\t]/).map(x=>x.trim());if(p.length<3)throw new Error(`項目 ${i+1} は 名前, 1回のbytes, 1秒の回数 で入力してね`);return{name:p[0]||`項目${i+1}`,bytes:positive(p[1],`項目 ${i+1} のbytes`,true),perSecond:positive(p[2],`項目 ${i+1} の回数`,true)}});if(!rows.length)throw new Error('割り当て項目を1件以上入力してね');if(rows.length>20)throw new Error('項目は20件までだよ');return rows}
function analyze(settings,sources){const fps=positive(settings.fps,'目標FPS'),heapMB=positive(settings.heapMB,'回収までの割り当て量'),pauseMs=positive(settings.pauseMs,'停止時間',true),budgetMs=1000/fps;const rows=sources.map(s=>({...s,bytesPerSecond:s.bytes*s.perSecond,bytesPerFrame:s.bytes*s.perSecond/fps}));const totalBps=rows.reduce((a,x)=>a+x.bytesPerSecond,0),totalPerFrame=totalBps/fps,thresholdBytes=heapMB*1024*1024,intervalSeconds=totalBps?thresholdBytes/totalBps:null,lostFrames=pauseMs?Math.ceil(pauseMs/budgetMs):0;rows.sort((a,b)=>b.bytesPerSecond-a.bytesPerSecond);return{settings:{fps,heapMB,pauseMs},summary:{totalKBps:round(totalBps/1024),bytesPerFrame:round(totalPerFrame),intervalSeconds:intervalSeconds===null?null:round(intervalSeconds),collectionsPerMinute:intervalSeconds?round(60/intervalSeconds):0,frameBudgetMs:round(budgetMs),lostFrames},rows:rows.map(x=>({...x,bytesPerSecond:round(x.bytesPerSecond),bytesPerFrame:round(x.bytesPerFrame),share:totalBps?round(x.bytesPerSecond/totalBps*100,1):0}))}}
function exportData(result){return{tool:'GC Pace Meter',version:1,createdAt:new Date().toISOString(),method:'入力した割り当て量と頻度からGC発生間隔を単純換算。実際のヒープ閾値、Incremental GC、ネイティブ割り当てはProfilerで確認する。',...result}}
root.GCPaceMeter={parseSources,analyze,exportData};
})(typeof window!=='undefined'?window:globalThis);
