const $=s=>document.querySelector(s),L=window.InputWindowLab,NS='amu-web-service-lab',SLUG='input-window-lab',PINGS=[];
let started=false,completed=false,tries=0,specials=new Set(),queued=false,lastPhase=0,jumpUntil=0,jumpKind='normal',origin=performance.now();
function metric(name){const img=new Image();PINGS.push(img);img.onload=img.onerror=()=>PINGS.splice(PINGS.indexOf(img),1);img.src=`https://api.counterapi.dev/v1/${NS}/${SLUG}-${name}/up?t=${Date.now()}`}
metric('view');try{if(!localStorage.getItem(`${SLUG}-counted`)){setTimeout(()=>{metric('visitor');localStorage.setItem(`${SLUG}-counted`,'1')},1200)}}catch(e){}
function config(){return L.normalize({coyoteMs:$('#coyote').value,bufferMs:$('#buffer').value})}
function begin(){if(!started){started=true;metric('start')}}
function finish(){if(!completed){completed=true;metric('complete')}}
function renderControls(){const c=config();$('#coyoteOut').value=c.coyoteMs+' ms';$('#bufferOut').value=c.bufferMs+' ms';$('#preset').textContent=L.presetText(c);$('#specials').textContent=specials.size;$('#badge').textContent=specials.size===2?'両方成功':specials.size===1?'あと1種類':'未検証'}
function attempt(){begin();tries++;$('#tries').textContent=tries;const phase=(performance.now()-origin)%L.CYCLE,kind=L.classifyPress(phase,config());if(kind==='buffer'){queued=true;$('#result').textContent='先行入力を受け付けた。着地でジャンプするよ。';jumpKind='buffer'}else if(kind==='miss'){$('#result').textContent='猶予の外だった。スライダーを広げるか、押す時刻を変えてね。';jumpUntil=0}else{jumpKind=kind;jumpUntil=performance.now()+520;$('#result').textContent=kind==='coyote'?'コヨーテジャンプ成功。足場を離れた後でも跳べた。':'接地中の通常ジャンプ。'}if(kind==='coyote'){specials.add(kind);renderControls()} }
function updateQueued(phase,now){if(queued&&lastPhase<L.LAND&&phase>=L.LAND){queued=false;jumpKind='buffer';jumpUntil=now+520;specials.add('buffer');$('#result').textContent='先行入力ジャンプ成功。着地と同時に跳べた。';renderControls()}if(specials.size===2)finish();lastPhase=phase}
const canvas=$('#game'),ctx=canvas.getContext('2d');
function roundRect(x,y,w,h,r,fill){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill()}
function draw(now){const phase=(now-origin)%L.CYCLE;updateQueued(phase,now);const d=devicePixelRatio||1,rect=canvas.getBoundingClientRect(),w=Math.max(320,rect.width),h=w*360/760;if(canvas.width!==Math.round(w*d)){canvas.width=Math.round(w*d);canvas.height=Math.round(h*d)}ctx.setTransform(canvas.width/760,0,0,canvas.height/360,0,0);ctx.clearRect(0,0,760,360);const grd=ctx.createLinearGradient(0,0,0,360);grd.addColorStop(0,'#10243a');grd.addColorStop(1,'#08111c');ctx.fillStyle=grd;ctx.fillRect(0,0,760,360);
  ctx.fillStyle='#ffffff10';for(let x=0;x<760;x+=38)ctx.fillRect(x,0,1,360);for(let y=0;y<360;y+=38)ctx.fillRect(0,y,760,1);
  const px=190,speed=.28,edgeX=px+(L.EDGE-phase)*speed,landX=px+(L.LAND-phase)*speed;roundRect(-80,260,edgeX+80,100,14,'#24445a');roundRect(landX,260,390,100,14,'#24445a');ctx.fillStyle='#5ee7d1';ctx.fillRect(-80,260,edgeX+80,5);ctx.fillRect(landX,260,390,5);
  const c=config(),coyoteW=c.coyoteMs*speed,bufferW=c.bufferMs*speed;ctx.globalAlpha=.8;ctx.fillStyle='#ffd166';ctx.fillRect(edgeX-coyoteW,249,coyoteW,7);ctx.fillStyle='#a88cff';ctx.fillRect(landX,249,bufferW,7);ctx.globalAlpha=1;
  const jumping=now<jumpUntil,jp=jumping?Math.sin(Math.max(0,1-(jumpUntil-now)/520)*Math.PI)*88:0;ctx.save();ctx.translate(px,235-jp);if(jumping)ctx.rotate(Math.sin((jumpUntil-now)/55)*.05);roundRect(-22,-43,44,43,12,jumpKind==='coyote'?'#ffd166':jumpKind==='buffer'?'#a88cff':'#5ee7d1');ctx.fillStyle='#07111b';ctx.fillRect(-11,-29,7,7);ctx.fillRect(6,-29,7,7);ctx.restore();
  const label=phase<L.EDGE?'接地中':phase<L.LAND?'空中のすき間':'着地後';$('#phaseLabel').textContent=label;requestAnimationFrame(draw)}
['coyote','buffer'].forEach(id=>$('#'+id).addEventListener('input',()=>{begin();renderControls()}));$('#jump').addEventListener('click',attempt);canvas.addEventListener('pointerdown',attempt);addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&!/INPUT|TEXTAREA|BUTTON/.test(e.target.tagName)){e.preventDefault();attempt()}});$('#copy').addEventListener('click',async()=>{begin();const text=L.presetText(config());try{await navigator.clipboard.writeText(text);$('#copy').textContent='コピーしたよ'}catch(e){const blob=new Blob([text],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='input-window-preset.json';a.click();$('#copy').textContent='JSONを保存したよ'}finish();setTimeout(()=>$('#copy').textContent='設定JSONをコピー',1400)});renderControls();requestAnimationFrame(draw);
