const $=s=>document.querySelector(s),L=window.LoopSeamLab,SLUG='loop-seam-lab',NS='amu-web-service-lab',PINGS=[];let ctx=null,samples=null,rate=44100,name='loop-sample',best=null,source=null,started=false,completed=false;
function metric(name){const image=new Image;PINGS.push(image);image.onload=image.onerror=()=>PINGS.splice(PINGS.indexOf(image),1);image.src=`https://api.counterapi.dev/v1/${NS}/${SLUG}-${name}/up?t=${Date.now()}`}
metric('view');try{if(!localStorage.getItem(`${SLUG}-counted`))setTimeout(()=>{metric('visitor');localStorage.setItem(`${SLUG}-counted`,'1')},1200)}catch(e){}
function context(){return ctx||(ctx=new(window.AudioContext||window.webkitAudioContext)())}
function bounds(){const n=samples.length,start=Math.max(2,Math.floor(Number($('#start').value))),end=Math.min(n-2,Math.floor(Number($('#end').value)));return{start,end}}
function sec(i){return(i/rate).toFixed(3)+' s'}
function updateTimes(){if(!samples)return;const b=bounds();$('#startTime').textContent=sec(b.start);$('#endTime').textContent=sec(b.end);draw()}
function draw(){if(!samples)return;const c=$('#wave'),g=c.getContext('2d'),w=c.width,h=c.height,b=bounds();g.fillStyle='#071015';g.fillRect(0,0,w,h);const x1=b.start/samples.length*w,x2=b.end/samples.length*w;g.fillStyle='rgba(113,223,200,.09)';g.fillRect(x1,0,x2-x1,h);g.strokeStyle='#1c3338';g.beginPath();g.moveTo(0,h/2);g.lineTo(w,h/2);g.stroke();g.strokeStyle='#78dfca';g.lineWidth=1.5;g.beginPath();const step=Math.max(1,Math.floor(samples.length/w));for(let x=0;x<w;x++){let lo=1,hi=-1;for(let i=x*step;i<Math.min(samples.length,(x+1)*step);i++){lo=Math.min(lo,samples[i]);hi=Math.max(hi,samples[i])}g.moveTo(x,(1-hi)*h/2);g.lineTo(x,(1-lo)*h/2)}g.stroke();g.strokeStyle='#ffca72';g.lineWidth=3;[x1,x2].forEach(x=>{g.beginPath();g.moveTo(x,0);g.lineTo(x,h);g.stroke()})}
function setAudio(data,sr,label){stop();samples=Float32Array.from(data);rate=sr;name=label.replace(/\.[^.]+$/,'')||'loop';best=null;for(const id of ['start','end'])$("#"+id).max=samples.length-2;$('#start').value=Math.floor(samples.length*.12);$('#end').value=Math.floor(samples.length*.88);$('#fileName').textContent=`${label} ・ ${sec(samples.length)}`;$('#apply').disabled=true;$('#play').disabled=false;$('#export').disabled=true;$('#summary').textContent='解析待ち';$('#score').textContent='—';$('#status').textContent='';updateTimes()}
function sample(){rate=44100;const duration=4,n=rate*duration,x=new Float32Array(n);for(let i=0;i<n;i++){const t=i/rate,env=.62+.18*Math.sin(2*Math.PI*.37*t);x[i]=env*(.55*Math.sin(2*Math.PI*110*t)+.23*Math.sin(2*Math.PI*221.7*t)+.08*Math.sin(2*Math.PI*443*t));if(i>n*.84)x[i]+=(i/n-.84)*.7}setAudio(x,rate,'generated-ambient-loop.wav')}
async function load(file){if(!file)return;try{const ab=await file.arrayBuffer(),decoded=await context().decodeAudioData(ab),x=new Float32Array(decoded.length);for(let ch=0;ch<decoded.numberOfChannels;ch++){const d=decoded.getChannelData(ch);for(let i=0;i<x.length;i++)x[i]+=d[i]/decoded.numberOfChannels}setAudio(x,decoded.sampleRate,file.name)}catch(e){$('#error').textContent='音声を読み込めなかった: '+e.message}}
function analyze(track=true){try{if(!samples)throw new Error('音声を選んでね');const b=bounds();if(b.end-b.start<rate*.08)throw new Error('ループ範囲を80ms以上にしてね');if(track&&!started){metric('start');started=true}const m=L.metrics(samples,b.start,b.end),radius=Math.max(20,Math.floor(rate*.03));best=L.findBest(samples,b.start,b.end,radius,Math.floor(rate*.08));$('#summary').textContent=m.grade;$('#score').textContent=m.score;$('#jump').textContent=m.jump.toFixed(4);$('#slope').textContent=m.slope.toFixed(4);$('#duration').textContent=sec(m.length);const gain=m.score-best.score;$('#suggestion').innerHTML=`現在の境界はスコア <b>${m.score}</b>。開始を <b>${sec(best.start)}</b>、終了を <b>${sec(best.end)}</b> に寄せると <b>${best.score}</b> まで改善する候補がある（±30ms探索、${gain}点改善）。`;$('#apply').disabled=false;$('#export').disabled=false;$('#error').textContent='';if(track&&!completed){metric('complete');completed=true}}catch(e){$('#error').textContent=e.message}}
function apply(){if(!best||!samples)return;$('#start').value=best.start;$('#end').value=best.end;updateTimes();analyze(false);$('#status').textContent='低ノイズ候補を適用したよ。'}
function stop(){if(source){try{source.stop()}catch(e){}source=null;$('#play').textContent='ループ試聴'}}
async function play(){if(source){stop();return}if(!samples)return;const ac=context();await ac.resume();const b=bounds(),buffer=ac.createBuffer(1,samples.length,rate);buffer.copyToChannel(samples,0);source=ac.createBufferSource();source.buffer=buffer;source.loop=true;source.loopStart=b.start/rate;source.loopEnd=b.end/rate;source.connect(ac.destination);source.onended=()=>{source=null;$('#play').textContent='ループ試聴'};source.start(0,b.start/rate);$('#play').textContent='停止'}
function save(){if(!samples)return;const b=bounds(),fade=Math.min(Math.floor(rate*.01),Math.floor((b.end-b.start)/3)),out=L.crossfade(samples,b.start,b.end,fade),blob=new Blob([L.encodeWav(out,rate)],{type:'audio/wav'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${name}-loop.wav`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);$('#status').textContent=`${sec(out.length)} / 末尾${(fade/rate*1000).toFixed(0)}msクロスフェードのWAVを保存したよ。`}
$('#sample').onclick=()=>{sample();analyze(true)};$('#file').onchange=e=>load(e.target.files[0]);$('#start').oninput=updateTimes;$('#end').oninput=updateTimes;$('#analyze').onclick=()=>analyze(true);$('#apply').onclick=apply;$('#play').onclick=play;$('#export').onclick=save;sample();analyze(false);
