(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.AlphaMipGuard=api})(typeof self!=='undefined'?self:this,function(){
  const clamp=(v,min,max)=>Math.max(min,Math.min(max,Number(v)||0));
  function downsample(alpha,width,height){const nw=Math.max(1,Math.ceil(width/2)),nh=Math.max(1,Math.ceil(height/2)),out=new Array(nw*nh);for(let y=0;y<nh;y++)for(let x=0;x<nw;x++){let sum=0,n=0;for(let dy=0;dy<2;dy++)for(let dx=0;dx<2;dx++){const sx=x*2+dx,sy=y*2+dy;if(sx<width&&sy<height){sum+=clamp(alpha[sy*width+sx],0,1);n++}}out[y*nw+x]=sum/n}return{alpha:out,width:nw,height:nh}}
  function coverage(alpha,cutoff){if(!alpha.length)return 0;return alpha.filter(a=>a>=cutoff).length/alpha.length}
  function preserveCutoff(alpha,target){let best=0,bestDiff=Infinity;for(let i=0;i<=100;i++){const c=i/100,d=Math.abs(coverage(alpha,c)-target);if(d<bestDiff){bestDiff=d;best=c}}return Number(best.toFixed(2))}
  function analyze(input){let alpha=Array.from(input.alpha||[],v=>clamp(v,0,1)),width=Math.max(1,Math.round(Number(input.width)||1)),height=Math.max(1,Math.round(Number(input.height)||1));if(alpha.length!==width*height)throw new Error('alpha length does not match dimensions');const cutoff=clamp(input.cutoff??.5,.01,.99),maxLevels=Math.max(1,Math.min(10,Math.round(input.levels||5))),base=coverage(alpha,cutoff),levels=[];let current={alpha,width,height};for(let level=0;level<maxLevels;level++){const cov=coverage(current.alpha,cutoff),loss=base?Math.max(0,(base-cov)/base):0,adjusted=preserveCutoff(current.alpha,base);levels.push({level,width:current.width,height:current.height,coverage:Number(cov.toFixed(4)),loss:Number(loss.toFixed(4)),adjustedCutoff:adjusted,alpha:current.alpha});if(current.width===1&&current.height===1)break;current=downsample(current.alpha,current.width,current.height)}const worst=Math.max(...levels.map(x=>x.loss)),risk=worst>.35?'high':worst>.12?'medium':'low';return{cutoff:Number(cutoff.toFixed(2)),baseCoverage:Number(base.toFixed(4)),risk,worstLoss:Number(worst.toFixed(4)),levels}}
  function report(input){const a=analyze(input);return{tool:'Alpha Mip Guard',generated_at:new Date().toISOString(),cutoff:a.cutoff,baseCoverage:a.baseCoverage,risk:a.risk,worstLoss:a.worstLoss,levels:a.levels.map(({alpha,...rest})=>rest),note:'ブラウザの2x2平均による近似。エンジン固有のフィルタ・圧縮・Alpha Coverage設定は実機で確認してください。'}}
  return{downsample,coverage,preserveCutoff,analyze,report};
});
