const $=s=>document.querySelector(s),L=window.KeyArtCropper,NS='amu-web-service-lab',SLUG='key-art-cropper',PINGS=[];
const formats=[{name:'ワイド',ratio:'16:9',w:640,h:360},{name:'ヘッダー',ratio:'2:1',w:640,h:320},{name:'スクエア',ratio:'1:1',w:480,h:480},{name:'ポートレート',ratio:'4:5',w:480,h:600}];let image=new Image(),started=false;
function metric(name){const img=new Image();PINGS.push(img);img.onload=img.onerror=()=>PINGS.splice(PINGS.indexOf(img),1);img.src=`https://api.counterapi.dev/v1/${NS}/${SLUG}-${name}/up?t=${Date.now()}`}
metric('view');try{if(!localStorage.getItem(`${SLUG}-counted`)){setTimeout(()=>{metric('visitor');localStorage.setItem(`${SLUG}-counted`,'1')},1200)}}catch(e){}
function begin(){if(!started){started=true;metric('start')}}
function sample(){const c=document.createElement('canvas');c.width=1200;c.height=800;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,1200,800);g.addColorStop(0,'#152b37');g.addColorStop(.52,'#ef5b3f');g.addColorStop(1,'#f1b84b');x.fillStyle=g;x.fillRect(0,0,1200,800);x.fillStyle='#fff7ed';x.beginPath();x.arc(610,330,145,0,Math.PI*2);x.fill();x.fillStyle='#18201d';x.font='900 92px system-ui';x.textAlign='center';x.fillText('YOUR GAME',600,635);x.font='700 30px system-ui';x.fillText('KEY VISUAL',600,685);return c.toDataURL()}
function draw(canvas,format,forSheet=false){const fx=Number($('#focusX').value)/100,fy=Number($('#focusY').value)/100,crop=L.coverCrop(image.naturalWidth,image.naturalHeight,format.w,format.h,fx,fy),ctx=canvas.getContext('2d');canvas.width=format.w;canvas.height=format.h;ctx.drawImage(image,crop.x,crop.y,crop.width,crop.height,0,0,format.w,format.h);if($('#safe').checked){const s=L.safeRect(format.w,format.h,.12);ctx.save();ctx.strokeStyle='rgba(255,255,255,.9)';ctx.lineWidth=Math.max(2,format.w/240);ctx.setLineDash([10,8]);ctx.strokeRect(s.x,s.y,s.width,s.height);ctx.restore()}if(forSheet){ctx.fillStyle='rgba(10,15,14,.72)';ctx.fillRect(0,0,format.w,38);ctx.fillStyle='white';ctx.font='700 18px system-ui';ctx.textAlign='left';ctx.fillText(`${format.name}  ${format.ratio}`,14,25)}}
function render(){ $('#xOut').value=$('#focusX').value+'%';$('#yOut').value=$('#focusY').value+'%';document.querySelectorAll('.card canvas').forEach((c,i)=>draw(c,formats[i]))}
$('#previews').innerHTML=formats.map((f,i)=>`<figure class="card"><div class="canvas-wrap"><canvas data-i="${i}"></canvas></div><figcaption>${f.name}<span>${f.ratio}</span></figcaption></figure>`).join('');
['focusX','focusY','safe'].forEach(id=>$('#'+id).addEventListener('input',()=>{begin();render()}));
$('#file').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;begin();const url=URL.createObjectURL(file),next=new Image();next.onload=()=>{if(image.src.startsWith('blob:'))URL.revokeObjectURL(image.src);image=next;$('#fileName').textContent=file.name;render()};next.src=url});
$('#download').addEventListener('click',()=>{begin();const sheet=document.createElement('canvas'),gap=24,title=86,w=1328,h=gap+title+360+gap+600+gap;sheet.width=w;sheet.height=h;const x=sheet.getContext('2d');x.fillStyle='#f2efe9';x.fillRect(0,0,w,h);x.fillStyle='#18201d';x.font='900 34px system-ui';x.fillText('KEY ART CROP REVIEW',gap,54);formats.forEach((f,i)=>{const c=document.createElement('canvas');draw(c,f,true);const px=i<2?gap+(i%2)*(640+gap):gap+(i-2)*(480+gap),py=i<2?gap+title:gap+title+360+gap;x.drawImage(c,px,py)});const a=document.createElement('a');a.download='key-art-crop-review.png';a.href=sheet.toDataURL('image/png');a.click();metric('complete')});
image.onload=render;image.src=sample();
