const $=s=>document.querySelector(s),C=window.ControlDeck,SLUG='control-deck',NS='amu-web-service-lab',PINGS=[];let started=false,completed=false,lastResult=null,nextId=1;
function metric(name){const img=new Image();PINGS.push(img);img.onload=img.onerror=()=>PINGS.splice(PINGS.indexOf(img),1);img.src=`https://api.counterapi.dev/v1/${NS}/${SLUG}-${name}/up?t=${Date.now()}`}
metric('view');try{if(!localStorage.getItem(`${SLUG}-counted`)){setTimeout(()=>{metric('visitor');localStorage.setItem(`${SLUG}-counted`,'1')},1200)}}catch(e){}
function begin(){if(!started){started=true;metric('start')}}function finish(){if(!completed){completed=true;metric('complete')}}
const defaults=[{name:'移動',keyboard:'WASD / Arrows',gamepad:'Left Stick',touch:'左スティック'},{name:'ジャンプ',keyboard:'Space',gamepad:'South Button',touch:'右ボタン'},{name:'決定',keyboard:'Enter',gamepad:'South Button',touch:'タップ'},{name:'キャンセル',keyboard:'Esc',gamepad:'East Button',touch:'戻る'},{name:'ポーズ',keyboard:'Esc',gamepad:'Menu',touch:'メニュー'}];
function addRow(data={name:'新しいアクション',keyboard:'',gamepad:'',touch:'',required:true}){const row=$('#rowTemplate').content.firstElementChild.cloneNode(true);row.dataset.id=`action-${nextId++}`;Object.entries(data).forEach(([key,value])=>{const input=row.querySelector(`[data-key="${key}"]`);if(!input)return;if(input.type==='checkbox')input.checked=value!==false;else input.value=value});row.querySelector('.remove').addEventListener('click',()=>{begin();row.remove();render()});row.querySelectorAll('input').forEach(input=>input.addEventListener('input',()=>{begin();render()}));$('#rows').append(row)}
function readConfig(){return{requiredDevices:[...document.querySelectorAll('.device:checked')].map(x=>x.value),actions:[...$('#rows').children].map(row=>{const data={id:row.dataset.id,bindings:{}};row.querySelectorAll('[data-key]').forEach(input=>{if(input.dataset.key==='required')data.required=input.checked;else if(input.dataset.key==='name')data.name=input.value;else data.bindings[input.dataset.key]=input.value});return data})}}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){lastResult=C.audit(readConfig());const s=lastResult.summary;$('#coverage').textContent=`${Math.round(s.coverage*100)}%`;$('#conflicts').textContent=`${s.conflictCount}件`;$('#missing').textContent=`${s.missingCount}枠`;const d=$('#diagnosis');d.className='diagnosis'+(s.conflictCount?' bad':s.missingCount?' warn':'');let issues=[];lastResult.conflicts.forEach(x=>issues.push(`<div class="issue"><b>競合</b> ${C.labels[x.device]}「${escapeHtml(x.binding)}」: ${x.actions.map(escapeHtml).join(' / ')}</div>`));lastResult.missing.forEach(x=>issues.push(`<div class="issue"><b>未設定</b> ${escapeHtml(x.action)}: ${C.labels[x.device]}</div>`));d.innerHTML=`<strong>${s.message}</strong>${issues.length?`<div class="issue-list">${issues.join('')}</div>`:'<div class="issue-list"><div class="issue">選択中のデバイスで必須アクションを実行できる状態だよ。</div></div>'}`}
$('#add').addEventListener('click',()=>{begin();addRow();render()});$('#audit').addEventListener('click',()=>{begin();render();$('#diagnosis').scrollIntoView({behavior:'smooth',block:'center'})});document.querySelectorAll('.device').forEach(input=>input.addEventListener('change',()=>{begin();render()}));$('#copy').addEventListener('click',()=>{begin();const text=C.exportText(readConfig()),area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();let copied=false;try{copied=document.execCommand('copy')}catch(e){}area.remove();$('#copyStatus').textContent=copied?'入力マップJSONをコピーしたよ。':'入力マップJSONを生成したよ。';finish()});defaults.forEach(addRow);render();
