(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.PathPaceLab=api})(typeof self!=='undefined'?self:this,function(){
  function point(p,t){const u=1-t,a=u*u*u,b=3*u*u*t,c=3*u*t*t,d=t*t*t;return{x:a*p[0].x+b*p[1].x+c*p[2].x+d*p[3].x,y:a*p[0].y+b*p[1].y+c*p[2].y+d*p[3].y,t}}
  function distance(a,b){return Math.hypot(b.x-a.x,b.y-a.y)}
  function lookup(p,steps=2000){const rows=[{...point(p,0),length:0}];let total=0;for(let i=1;i<=steps;i++){const q=point(p,i/steps);total+=distance(rows.at(-1),q);rows.push({...q,length:total})}return{rows,total}}
  function atLength(table,target){const rows=table.rows;if(target<=0)return rows[0];if(target>=table.total)return rows.at(-1);let lo=0,hi=rows.length-1;while(lo+1<hi){const m=(lo+hi)>>1;if(rows[m].length<target)lo=m;else hi=m}const a=rows[lo],b=rows[hi],r=(target-a.length)/(b.length-a.length||1);return{x:a.x+(b.x-a.x)*r,y:a.y+(b.y-a.y)*r,t:a.t+(b.t-a.t)*r,length:target}}
  function analyze(p,count=16){if(!Array.isArray(p)||p.length!==4||p.some(q=>!Number.isFinite(q.x)||!Number.isFinite(q.y)))throw new Error('制御点4個の座標を確認してください');count=Math.round(Number(count));if(count<4||count>100)throw new Error('分割数は4〜100にしてください');const table=lookup(p),parameter=[],paced=[];for(let i=0;i<=count;i++){parameter.push(point(p,i/count));paced.push(atLength(table,table.total*i/count))}function stats(points){const lengths=points.slice(1).map((q,i)=>distance(points[i],q)),mean=lengths.reduce((a,b)=>a+b,0)/lengths.length,variance=lengths.reduce((a,b)=>a+(b-mean)**2,0)/lengths.length;return{lengths,mean,cv:Math.sqrt(variance)/mean,min:Math.min(...lengths),max:Math.max(...lengths),ratio:Math.max(...lengths)/Math.min(...lengths)}}return{total:table.total,parameter,paced,parameterStats:stats(parameter),pacedStats:stats(paced)}}
  function csv(result){let sum=0;return'index,t,x,y,distance\n'+result.paced.map((p,i)=>{const d=i?distance(result.paced[i-1],p):0;sum+=d;return[i,+p.t.toFixed(7),+p.x.toFixed(4),+p.y.toFixed(4),+sum.toFixed(4)].join(',')}).join('\n')+'\n'}
  return{point,distance,lookup,analyze,csv}
});
