(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.CurveOvershootGuard=api})(typeof self!=='undefined'?self:this,function(){
  function parse(text){const lines=String(text).trim().split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)throw new Error('ヘッダーと2行以上のキーを入力してください');const header=lines[0].split(',').map(x=>x.trim().toLowerCase()),find=(names)=>header.findIndex(h=>names.includes(h));const ti=find(['time','t','時刻']),vi=find(['value','v','値']),ii=find(['intangent','in_tangent','in']),oi=find(['outtangent','out_tangent','out']);if(ti<0||vi<0)throw new Error('time,value列が必要です');const keys=lines.slice(1).map((line,index)=>{const p=line.split(',').map(x=>x.trim()),time=Number(p[ti]),value=Number(p[vi]),inTangent=ii<0?0:Number(p[ii]),outTangent=oi<0?0:Number(p[oi]);if(![time,value,inTangent,outTangent].every(Number.isFinite))throw new Error(`${index+2}行目に数値以外があります`);return{time,value,inTangent,outTangent}}).sort((a,b)=>a.time-b.time);if(keys.length<2)throw new Error('キーは2個以上必要です');for(let i=1;i<keys.length;i++)if(keys[i].time<=keys[i-1].time)throw new Error('timeは重複せず昇順にしてください');return keys}
  function coefficients(a,b){const h=b.time-a.time;return{h,a:2*a.value-2*b.value+h*(a.outTangent+b.inTangent),b:-3*a.value+3*b.value-h*(2*a.outTangent+b.inTangent),c:h*a.outTangent,d:a.value}}
  function evaluate(a,b,time){const q=coefficients(a,b),u=Math.max(0,Math.min(1,(time-a.time)/q.h));return((q.a*u+q.b)*u+q.c)*u+q.d}
  function rootsInUnit(A,B,C){const out=[];if(Math.abs(A)<1e-12){if(Math.abs(B)>1e-12){const x=-C/B;if(x>1e-9&&x<1-1e-9)out.push(x)}return out}const disc=B*B-4*A*C;if(disc<0)return out;const s=Math.sqrt(disc);for(const x of [(-B+s)/(2*A),(-B-s)/(2*A)])if(x>1e-9&&x<1-1e-9&&!out.some(v=>Math.abs(v-x)<1e-8))out.push(x);return out.sort((x,y)=>x-y)}
  function analyze(keys){if(!Array.isArray(keys)||keys.length<2)throw new Error('キーは2個以上必要です');const segments=[];let maxOvershoot=0;for(let i=0;i<keys.length-1;i++){const p=keys[i],n=keys[i+1],q=coefficients(p,n),lo=Math.min(p.value,n.value),hi=Math.max(p.value,n.value),extrema=rootsInUnit(3*q.a,2*q.b,q.c).map(u=>{const value=((q.a*u+q.b)*u+q.c)*u+q.d,amount=Math.max(0,value-hi,lo-value);maxOvershoot=Math.max(maxOvershoot,amount);return{time:p.time+u*q.h,value,amount}});segments.push({index:i+1,from:p.time,to:n.time,extrema,overshoot:Math.max(0,...extrema.map(x=>x.amount))})}return{segments,maxOvershoot,problemSegments:segments.filter(s=>s.overshoot>1e-7).length}}
  function clampMonotone(keys){const n=keys.length,d=[];for(let i=0;i<n-1;i++)d.push((keys[i+1].value-keys[i].value)/(keys[i+1].time-keys[i].time));const m=new Array(n);m[0]=d[0];m[n-1]=d[n-2];for(let i=1;i<n-1;i++)m[i]=d[i-1]*d[i]<=0?0:(2*d[i-1]*d[i])/(d[i-1]+d[i]);for(let i=0;i<n-1;i++){if(Math.abs(d[i])<1e-12){m[i]=m[i+1]=0;continue}const a=m[i]/d[i],b=m[i+1]/d[i],sum=a*a+b*b;if(sum>9){const scale=3/Math.sqrt(sum);m[i]=scale*a*d[i];m[i+1]=scale*b*d[i]}}return keys.map((k,i)=>({...k,inTangent:m[i],outTangent:m[i]}))}
  function samples(keys,perSegment=48){const out=[];for(let i=0;i<keys.length-1;i++)for(let j=0;j<perSegment;j++){const time=keys[i].time+(keys[i+1].time-keys[i].time)*j/perSegment;out.push({time,value:evaluate(keys[i],keys[i+1],time)})}out.push({time:keys.at(-1).time,value:keys.at(-1).value});return out}
  function csv(keys){return 'time,value,inTangent,outTangent\n'+keys.map(k=>[k.time,k.value,+k.inTangent.toFixed(6),+k.outTangent.toFixed(6)].join(',')).join('\n')+'\n'}
  return{parse,evaluate,analyze,clampMonotone,samples,csv}
});
