(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.AssetPathGuard=api})(typeof self!=='undefined'?self:this,function(){
  const RESERVED=/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i;
  const EXTENSIONS=new Set(['png','jpg','jpeg','webp','gif','svg','psd','wav','mp3','ogg','flac','fbx','obj','gltf','glb','prefab','mat','anim','controller','shader','ttf','otf','json','csv','txt']);
  function cleanLine(line){return String(line||'').trim().replace(/^['"]|['"]$/g,'')}
  function safeSegment(segment,style='snake'){const dot=segment.lastIndexOf('.'),stem=dot>0?segment.slice(0,dot):segment,ext=dot>0?segment.slice(dot).toLowerCase():'';let s=stem.normalize('NFKC').replace(/([a-z0-9])([A-Z])/g,'$1 $2').replace(/[^\p{L}\p{N}]+/gu,' ').trim().toLowerCase();const join=style==='kebab'?'-':'_';s=s.replace(/\s+/g,join)||'unnamed';if(RESERVED.test(s))s=`_${s}`;return s+ext}
  function proposedPath(path,style='snake'){return path.replace(/\\/g,'/').split('/').filter(Boolean).map(s=>safeSegment(s,style)).join('/')}
  function inspect(text,style='snake'){const paths=String(text||'').split(/\r?\n/).map(cleanLine).filter(Boolean),items=[],seen=new Map();for(const path of paths){const normalized=path.replace(/\\/g,'/'),segments=normalized.split('/').filter(Boolean),name=segments.at(-1)||'',dot=name.lastIndexOf('.'),ext=dot>0?name.slice(dot+1):'',issues=[];if(path.includes('\\'))issues.push({level:'warn',code:'separator',message:'バックスラッシュを含む'});if(/\s/.test(path))issues.push({level:'warn',code:'space',message:'空白を含む'});if(/[<>:"|?*]/.test(path.replace(/^[A-Za-z]:/,'')))issues.push({level:'error',code:'forbidden',message:'移植性の低い記号を含む'});if(segments.some(s=>/[. ]$/.test(s)))issues.push({level:'error',code:'trailing',message:'末尾が空白またはピリオド'});if(segments.some(s=>RESERVED.test(s)))issues.push({level:'error',code:'reserved',message:'Windows予約名を含む'});if(ext&&ext!==ext.toLowerCase())issues.push({level:'warn',code:'extension-case',message:'拡張子が小文字でない'});if(!ext)issues.push({level:'info',code:'no-extension',message:'拡張子なし'});else if(!EXTENSIONS.has(ext.toLowerCase()))issues.push({level:'info',code:'unusual-extension',message:`未登録の拡張子 .${ext}`});const key=normalized.toLocaleLowerCase('en-US');if(seen.has(key)){issues.push({level:'error',code:'case-collision',message:`大文字小文字を無視すると「${seen.get(key)}」と衝突`})}else seen.set(key,path);const proposed=proposedPath(path,style);items.push({path,normalized,name,ext:ext.toLowerCase(),issues,proposed,changed:proposed!==normalized})}const counts={error:0,warn:0,info:0};items.forEach(i=>i.issues.forEach(x=>counts[x.level]++));const extensions={};items.forEach(i=>{const e=i.ext||'(none)';extensions[e]=(extensions[e]||0)+1});return{items,counts,extensions,total:items.length,clean:items.filter(i=>!i.issues.some(x=>x.level==='error'||x.level==='warn')).length,renameCount:items.filter(i=>i.changed).length}}
  function plan(result){return result.items.filter(i=>i.changed).map(i=>`${i.path} -> ${i.proposed}`).join('\n')}
  return{cleanLine,safeSegment,proposedPath,inspect,plan};
});
