(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ShaderVariantSieve=api})(typeof self!=='undefined'?self:this,function(){
  const clean=s=>String(s||'').trim();
  function parseGroups(text){return clean(text).split(/\r?\n/).map(clean).filter(Boolean).map((line,index)=>{const parts=line.split('=');if(parts.length<2)throw new Error(`${index+1}行目: GROUP = A | B の形式で入力`);const name=clean(parts.shift());const options=parts.join('=').split('|').map(clean).filter(Boolean);if(!name||options.length<2)throw new Error(`${index+1}行目: グループ名と2個以上の選択肢が必要`);return{name,options:[...new Set(options)]}})}
  function parseToggles(text){return [...new Set(clean(text).split(/[\n,]/).map(clean).filter(Boolean))]}
  function parseRules(text){return clean(text).split(/\r?\n/).map(clean).filter(Boolean).map((line,index)=>{const terms=[...new Set(line.split('+').map(clean).filter(Boolean))];if(terms.length<2)throw new Error(`${index+1}行目: KEYWORD + KEYWORD の形式で入力`);return terms})}
  function product(values){return values.reduce((a,b)=>a*b,1)}
  function enumerate(groups,toggles,limit=262144){const theoretical=product(groups.map(g=>g.options.length))*Math.pow(2,toggles.length);if(theoretical>limit)throw new Error(`組み合わせが ${theoretical.toLocaleString()} 件を超えるため、グループを分割してね`);let rows=[[]];groups.forEach(group=>{rows=rows.flatMap(row=>group.options.map(option=>option==='OFF'||option==='-'?row.slice():row.concat(option)))});toggles.forEach(toggle=>{rows=rows.flatMap(row=>[row.slice(),row.concat(toggle)])});return{rows,theoretical}}
  function analyze(config){const groups=config.groups||[],toggles=config.toggles||[],rules=config.rules||[],passes=Math.max(1,Math.floor(Number(config.passes)||1)),platforms=Math.max(1,Math.floor(Number(config.platforms)||1));if(!groups.length&&!toggles.length)throw new Error('グループか独立キーワードを1つ以上入力してね');const built=enumerate(groups,toggles),blocked=[],kept=[];built.rows.forEach(keywords=>{const set=new Set(keywords),rule=rules.find(r=>r.every(k=>set.has(k)));(rule?blocked:kept).push({keywords,rule:rule||null})});const combinations=kept.length,variants=combinations*passes*platforms,theoreticalVariants=built.theoretical*passes*platforms,reduction=theoreticalVariants?blocked.length/built.theoretical:0;const dimensions=[...groups.map(g=>({name:g.name,type:'group',multiplier:g.options.length,detail:g.options.join(' / ')})),...toggles.map(t=>({name:t,type:'toggle',multiplier:2,detail:'ON / OFF'}))].sort((a,b)=>b.multiplier-a.multiplier);const allKeywords=[...new Set(groups.flatMap(g=>g.options).concat(toggles).filter(x=>x!=='OFF'&&x!=='-'))];const frequency=allKeywords.map(keyword=>({keyword,count:kept.filter(row=>row.keywords.includes(keyword)).length})).sort((a,b)=>b.count-a.count||a.keyword.localeCompare(b.keyword));const level=variants>10000?'high':variants>1000?'medium':'low';return{groups,toggles,rules,passes,platforms,theoreticalCombinations:built.theoretical,combinations,blocked:blocked.length,theoreticalVariants,variants,reduction,dimensions,frequency,examples:kept.slice(0,8).map(x=>x.keywords),level}}
  function exportData(result){return{generated_at:new Date().toISOString(),model:'keyword combination pre-build estimate',assumptions:['Each group selects exactly one option; OFF and - add no keyword','Each independent keyword has ON and OFF states','Pass and platform multipliers are assumed independent','Engine- and pipeline-specific built-in variants are not included'],summary:{theoretical_combinations:result.theoreticalCombinations,kept_combinations:result.combinations,blocked_by_rules:result.blocked,passes:result.passes,platforms:result.platforms,estimated_variants:result.variants,reduction_percent:+(result.reduction*100).toFixed(1)},dimensions:result.dimensions,skip_rules:result.rules,example_kept_keyword_sets:result.examples,checklist:['Confirm actual variant count in engine build logs','Convert impossible combinations into stripping rules','Test one representative material per retained keyword set','Recalculate when adding a keyword, pass, or target platform']}}
  return{parseGroups,parseToggles,parseRules,enumerate,analyze,exportData};
});
