const $=s=>document.querySelector(s),P=window.PatchNoteForge,NS='amu-web-service-lab',SLUG='patch-note-forge',PINGS=[];let output='',started=false;
function metric(name){const img=new Image();PINGS.push(img);img.onload=img.onerror=()=>PINGS.splice(PINGS.indexOf(img),1);img.src=`https://api.counterapi.dev/v1/${NS}/${SLUG}-${name}/up?t=${Date.now()}`}
metric('view');try{if(!localStorage.getItem(`${SLUG}-counted`)){setTimeout(()=>{metric('visitor');localStorage.setItem(`${SLUG}-counted`,'1')},1200)}}catch(e){}
$('#date').value=new Date().toISOString().slice(0,10);
$('#source').addEventListener('input',()=>{if(!started&&$('#source').value.trim()){started=true;metric('start')}});
$('#sample').addEventListener('click',()=>{$('#source').value='feat(ui): add photo mode\nfix(save): resolve crash when loading slot #42\nperf: reduce scene loading time\nchore: update build dependencies\nfeat: add photo mode';$('#version').value='v1.2.0';$('#source').dispatchEvent(new Event('input'));generateNotes()});
function generateNotes(){const source=$('#source').value;if(!source.trim()){$('#summary').textContent='変更ログを1行以上入力してね';return}const result=P.render(source,{title:$('#title').value,version:$('#version').value,date:$('#date').value,includeInternal:$('#internal').checked});if(!result.total){$('#summary').textContent='公開向けの変更が見つからなかったよ';return}output=result.markdown;$('#preview').textContent=output;$('#summary').textContent=`${result.total}件を整形・重複${result.duplicates}件を除外`;$('#copy').disabled=$('#download').disabled=false;metric('complete')}
$('#copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(output);$('#copy').textContent='コピー済み';setTimeout(()=>$('#copy').textContent='コピー',1400)}catch(e){const r=document.createRange();r.selectNodeContents($('#preview'));getSelection().removeAllRanges();getSelection().addRange(r)}});
$('#download').addEventListener('click',()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([output],{type:'text/markdown'}));a.download='patch-notes.md';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)});
