const $=s=>document.querySelector(s),L=window.EaseCurveLab,SLUG='ease-curve-lab',NS='amu-web-service-lab',PINGS=[];let started=false,completed=false,raf=0;
function metric(name){const img=new Image();PINGS.push(img);img.onload=img.onerror=()=>PINGS.splice(PINGS.indexOf(img),1);img.src=`https://api.counterapi.dev/v1/${NS}/${SLUG}-${name}/up?t=${Date.now()}`}
metric('view');try{if(!localStorage.getItem(`${SLUG}-counted`)){setTimeout(()=>{metric('visitor');localStorage.setItem(`${SLUG}-counted`,'1')},1200)}}catch(e){}
function begin(){if(!started){started=true;metric('start')}}function finish(){if(!completed){completed=true;metric('complete')}}
const ids=['x1','y1','x2','y2'],canvas=$('#curve'),ctx=canvas.getContext('2d');function curve(){return ids.map(id=>+$('#'+id).value)}
function setCurve(values){ids.forEach((id,i)=>{$('#'+id).value=values[i]});render()}
function render(){const c=curve(),a=L.analyze(c),w=canvas.width,h=canvas.height,p=48,sx=x=>p+x*(w-p*2),sy=y=>h-p-y*(h-p*2);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#292c33';ctx.lineWidth=1;for(let i=0;i<=4;i++){const x=sx(i/4),y=sy(i/4);ctx.beginPath();ctx.moveTo(x,p);ctx.lineTo(x,h-p);ctx.stroke();ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(w-p,y);ctx.stroke()}ctx.strokeStyle='#666b74';ctx.setLineDash([7,7]);ctx.beginPath();ctx.moveTo(sx(0),sy(0));ctx.lineTo(sx(c[0]),sy(c[1]));ctx.moveTo(sx(1),sy(1));ctx.lineTo(sx(c[2]),sy(c[3]));ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#ffb44a';ctx.lineWidth=5;ctx.beginPath();L.samples(c,101).forEach((r,i)=>(i?ctx.lineTo(sx(r.time),sy(r.value)):ctx.moveTo(sx(r.time),sy(r.value))));ctx.stroke();[[c[0],c[1]],[c[2],c[3]]].forEach(([x,y])=>{ctx.fillStyle='#f3f0e8';ctx.beginPath();ctx.arc(sx(x),sy(y),7,0,Math.PI*2);ctx.fill()});ids.forEach(id=>$('#'+id+'Out').value=(+$('#'+id).value).toFixed(2));$('#durationOut').value=$('#duration').value+'ms';$('#midValue').textContent=Math.round(a.mid*100)+'%';$('#speedValue').textContent=a.maxSpeed.toFixed(2)+'×';$('#character').textContent=a.character}
function play(){begin();cancelAnimationFrame(raf);const start=performance.now(),duration=+$('#duration').value,travel=$('.lane').clientWidth-100,c=curve();function frame(now){const t=Math.min(1,(now-start)/duration);$('#curveDot').style.transform=`translateX(${L.solve(c,t)*travel}px)`;$('#linearDot').style.transform=`translateX(${t*travel}px)`;if(t<1)raf=requestAnimationFrame(frame)}raf=requestAnimationFrame(frame)}
ids.forEach(id=>$('#'+id).addEventListener('input',()=>{begin();$('#preset').value='custom';render()}));$('#duration').addEventListener('input',()=>{begin();render()});$('#preset').addEventListener('change',e=>{if(e.target.value!=='custom'){begin();setCurve(L.PRESETS[e.target.value]);play()}});$('#play').addEventListener('click',play);$('#export').addEventListener('click',()=>{begin();const text=L.exportText(curve(),+$('#duration').value);$('#code').textContent=text;$('#code').hidden=false;const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();const copied=document.execCommand('copy');area.remove();$('#status').textContent=copied?'実装コードを表示し、コピーしたよ。':'実装コードを表示したよ。';finish()});setCurve(L.PRESETS.ease);setTimeout(play,500);
